### ISSUE TITLE
dart format should preserve vertically-aligned formatting

### ISSUE THREAD

**Issue by chipweinberger** [dart-lang/dart_style#1252] opened 2023-08-22 06:06 UTC
Dart format should not make carefully considered indentation harder to read.

In practice I think comments that are vertically aligned should be ignored, or there should be some opt-out.

Potentially, vertically aligned comments should be the default.

**before formatting:**
```
enum BmAdapterStateEnum {
  unknown,      // 0
  unavailable,  // 1
  unauthorized, // 2
  turningOn,    // 3
  on,           // 4
  turningOff,   // 5
  off,          // 6
}
```

**after formatting:**
```
enum BmAdapterStateEnum {
  unknown, // 0
  unavailable, // 1
  unauthorized, // 2
  turningOn, // 3
  on, // 4
  turningOff, // 5
  off, // 6
}
```

**Comment by srawlins** [comment] 2023-08-22 13:59
Duplicate of https://github.com/dart-lang/dart_style/issues/48

**Closed** 2023-08-22 20:05 UTC
