### ISSUE TITLE
Continued string should be indented or left intact

### ISSUE THREAD

**Issue by rkj** [dart-lang/dart_style#233] opened 2015-04-08 01:49 UTC
Input:
```
@Component(
    selector: "column-customizer",
    templateUrl: "package:some.long.packages.names.column_customizer/"
                 "column_customizer.html",
    cssUrl: "package:some.long.packages.names.column_customizer/"
            "column_customizer.scss.css",
    visibility: Visibility.CHILDREN)
class ColumnCustomizerComponent extends BaseDrawerComponent {
}
```
After formatting:
```
@Component(
    selector: "column-customizer",
    templateUrl: "package:some.long.packages.names.column_customizer/"
    "column_customizer.html",
    cssUrl: "package:some.long.packages.names.column_customizer/"
    "column_customizer.scss.css",
    visibility: Visibility.CHILDREN)
class ColumnCustomizerComponent extends BaseDrawerComponent {}
```

**Comment by munificent** [comment] 2015-11-05 23:52
Duplicate of #220.

**Closed by munificent** 2015-11-05 23:52 UTC
Labels: common, difficult, meh, risky
