### ISSUE TITLE
Inserting a block-comment before a property call chain wraps each chained element

### ISSUE THREAD

**Issue by srawlins** [dart-lang/dart_style#1628] opened 2024-12-17 20:40 UTC
I was surprised by this in the new formatting. Here is an input text:

```dart
bool f(bool b, int i) {
  return // Check b.
  b == true || i.isEven;
}
```

The formatter likes all that code on one line. If I want to add a comment for the `i.isEven` expression, then it insists on splitting:

```dart
bool f(bool b, int i) {
  return // Check b.
  b == true ||
          // Check i.
          i
          .isEven;
}
```

🤕 Ouch. If this is intentional, I'll trust your research, and you can close.

**Comment by munificent** [comment] 2024-12-17 23:10
Yeah, the new formatter sometimes doesn't know what to do with comments in unusual places. It tends to attach them to the subsequent token, which is always owned by the deepest subexpression. That in turn means that subexpression contains a newline (from the line comment) which forces all of the surrounding expressions to split.

I kept running into these bugs and finally in #1615 found a more systematic way to handle them. It looks like this issue is fixed on the main branch already, so it seems #1615 is doing its job. I'll add a regression test for this.

**Comment by srawlins** [comment] 2024-12-17 23:25
Ah I didn't check closed bugs. Thanks Bob!

**Closed** 2024-12-17 23:34 UTC
