### ISSUE TITLE
extra linebreak in variabledeclarationlist

### ISSUE THREAD

**Issue by jmesserly** [dart-lang/dart_style#155] opened 2015-01-30 21:06 UTC
formatter made this change which I did not expect:
```diff
-    var from = node.baseType, to = node.convertedType;
+    var from = node.baseType,
+        to = node.convertedType;
```

**Comment by munificent** [comment] 2015-01-31 19:23
This is working as intended. If you declare multiple variables *with initializers* in a single declaration, each gets its own line.

**Comment by jmesserly** [comment] 2015-02-02 16:35
errr, okay, but the whole point was to have it be on one line :).
is this covered in the style guide somewhere or a previous discussion?

it's not over the 80 col limit, so i'm not sure why the formatter would change this

**Comment by munificent** [comment] 2015-02-02 17:19
> is this covered in the style guide somewhere or a previous discussion?

Now that you mention it, no I don't think it was. The old formatter always worked this way. My personal preference was in line with it, so I just preserved that behavior.

Do you really feel it adds a lot of value to allow multiple initialized variables on one line? I find it makes it really easy to miss the later variables. If you don't see the `,` in your example, it's very easy to not see that `to` is being declared at all.

I also feel it's a little too similar to something like:

```dart
var from = node(baseType, to = node.convertedType);
```

Now the `,` means something totally different. If you'd like, we can have a wider discussion about this, but I really do feel the current style rule leads to more readable code. I think people need to very easily scan code to see what variables are in scope, and burying them in the middle of a line makes that a lot harder.

**Comment by jmesserly** [comment] 2015-02-02 17:34
> Do you really feel it adds a lot of value to allow multiple initialized variables on one line?

yes, that's what I wanted to write it.

>  also feel it's a little too similar to something like:
> `var from = node(baseType, to = node.convertedType);`

one can make any expression confusing by swapping dots and parens :)
`var stringSource = new StringSource(source.text, source.uri);`
could be easily confused with
`var stringSource = new StringSource(source(text, source.uri));`

(grabbed a random line from dart_style, but you could do that transform to almost any line of dart code)

One could also imagine a formatter that does:

````
foo(bar, baz)
// formats to:
foo(
  bar,
  baz
)
````

I'm glad we don't do that. Sometimes putting things on the same line is good

> If you'd like, we can have a wider discussion about this, but I really do feel the current style rule leads to more readable code. 

dart_style is essentially banning variable declaration lists by formatting them like this. The only reason they're useful is to do more than one in a single line.

I thought it was worth some discussion, hence opening an issue. Didn't expect it to be immediately closed :(

**Comment by munificent** [comment] 2015-02-02 20:30
> dart_style is essentially banning variable declaration lists by formatting them like this.

Not so. It's banning declaration lists *with initializers*. This is fine:

```dart
var a, b, c;
```

> Didn't expect it to be immediately closed :(

I closed it just because the behavior was deliberate. From that perspective, it's a not a bug. As a request to change the intended behavior, that's different. I'll re-open and retarget the bug for that. Before I do it, though, I think we need to have a larger discussion to see how people feel it should behave.

**Comment by jmesserly** [comment] 2015-02-02 20:58
thanks :)  yeah that's fair... it's definitely an enhancement request, not a bug in the current impl. If others don't agree then no reason to change behavior.

> Not so. It's banning declaration lists *with initializers*. This is fine:
> ```dart
var a, b, c;
```

Generally variables should have initializers whenever possible right?

btw also, feel free to mark this bug low-pri. For now I can workaround by just avoiding the variable list pattern and `s/,/;\nvar/`

Just noticed a related enhancement case, maybe it is a different issue/discussion?

```diff
-      out..write('.')..write(node.methodName.name);
+      out
+        ..write('.')
+        ..write(node.methodName.name);
```

Here's the chain of thought:
* `left + "." + right` is pretty normal in languages without interpolation.
* With a StringBuilder/Buffer it becomes `sb.add(left).add('.').add(right)`.
* In Dart we decided `return this` all over in types like StringBuffer was excessive, so instead introduced cascades. So it becomes `sb..add(left)..add('.')..add(right)`
* but now formatter treats it differently. This would encourage me to use methods and make my "pretty printer" type `return this` everywhere.

Not sure if that's the intent but it seems like the different features aren't adding up quite right.

**Comment by munificent** [comment] 2015-02-02 21:30
> In Dart we decided return this all over in types like StringBuffer was excessive, so instead introduced cascades.

I don't remember the verbosity of `return this;` being a motivation. There were two motivations for cascades that I recall:

1. Jacob and co. wanted them for builders for working with the DOM API. At the time, our focus was on producing an API as terse and powerful as [method chaining in jQuery](http://ejohn.org/blog/ultra-chaining-with-jquery/). We didn't want to just use chained methods because getters and setters seemed like a more natural fit for Dart.

2. Some APIs that you may want to chain already return another value that's useful sometimes. In other words, for a single method, sometimes you want `return this` so you can chain, and some times you want it to return some other value. The canonical example Josh Bloch brought up was `.remove()`. It returns the removed item, which is handy sometimes. But it's also nice to be able to chain a bunch of `.remove(a).remove(b)` calls. Cascades let you select that at that callsite.

In either case, the syntax they chose gets unreadable very quickly, *especially* in the presence of getters and setters. (Ironic given that getters and setters where the motivation for adding cascades...) When they put cascades in the spec, I recall Gilad and Lars saying that they get hard to read if you don't split them across lines.

So the formatter's rule is that if you cascade more than one call, each gets moved to its own line like the language folks suggested. I realize that begs the question why use cascades to begin with, but I didn't design the syntax, I just format it.

The formatter could try to be more sophisticated and distinguish between cascaded method calls versus cascaded getters and setters and allow multiple of the former on one line. I'm not sure if the value is worth the extra complexity. Either way, this is absolutely a separate issue from this one. :)

**Comment by munificent** [comment] 2015-06-09 20:32
I asked around the office, and the general vibe is that declaring multiple variables on one line with initializers is fine if they fit, so I'll leave this open as a request to change that.

(I'm personally agnostic because I always declare variables separates.)

**Closed** 2015-06-10 17:39 UTC
Labels: enhancement
