### ISSUE TITLE
Destructive dartfmt on part of uri files.

### ISSUE THREAD

**Issue by jacob314** [dart-lang/dart_style#617] opened 2017-04-17 17:54 UTC
Repro:
```sdk/tools/sdks/linux/dart-sdk/bin/dartfmt -w tests/language/part_of_uri2_part.dart```

Line 
```dart
part of "part_of_uri2_test.dart";
```
Changes to
```dart
part of ;
````

**Comment by floitschG** [comment] 2017-04-19 13:45
Duplicate of #615.

**Closed by floitschG** 2017-04-19 13:45 UTC
Labels: bug
