### ISSUE TITLE
Provide an option to change default indentation size and/or  braces style

### ISSUE THREAD

**Issue by koldoon** [dart-lang/dart_style#1050] opened 2021-09-03 04:05 UTC
Two-spaces indentation together with flow-like if-then-else style is a disaster! I honestly tried to get used to it for two years or so but no-no-no! Such code is just... not readable!

Example:
```
    try {
      setState(() => error = null);
      await auth.logIn();
      await AppRouting.navigateHome(context);
    } on AuthError catch (err) {
      logger.warn('AuthError (${err.type})');
      await AppRouting.navigateLogin(context);
    } on Exception catch (err) {
      logger.error('Exception (${err.toString()})');
      setState(() => error = err);
    }
```

It requires a huge amount of attention to jump eyes between column where `try` starts and `on` statement begins. The same with if-then-else. Together with two spaces indentation the code is just.. being "blended" or "blurred" and it becomes difficult to find appropriate flow control block! Many teams would prefer Stroustrup braces style, when `on`, `else` and other flow control keywords are placed on a new line like this:

```
    try {
      setState(() => error = null);
      await auth.logIn();
      await AppRouting.navigateHome(context);
    }
    on AuthError catch (err) {
      logger.warn('AuthError (${err.type})');
      await AppRouting.navigateLogin(context);
    }
    on Exception catch (err) {
      logger.error('Exception (${err.toString()})');
      setState(() => error = err);
    }

    if (condition()) {
      doSmth();
      updateState();
    }
    else {
      doSmthElse();
    }
```

The ONLY useful case for the "merged" style might be better is when there is a single statement in each control flow block but this is rather an exception than a rule.

Four spaces instead of two also might be helpful:

```
    try {
        setState(() => error = null);
        await auth.logIn();
        await AppRouting.navigateHome(context);
    } on AuthError catch (err) {
        logger.warn('AuthError (${err.type})');
        await AppRouting.navigateLogin(context);
    } on Exception catch (err) {
        logger.error('Exception (${err.toString()})');
        setState(() => error = err);
    }
```

In this case condition statement is also emphesized against the controlled code block and makes reading a little bit easier.

**Comment by munificent** [comment] 2021-09-07 18:43
Duplicate of #534 and #934. See also https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-configure-it.

**Closed by munificent** 2021-09-07 18:43 UTC
