### ISSUE TITLE
dartfmt unnecessarily puts long split string literal on separate line

### ISSUE THREAD

**Issue by tetkin-g** [dart-lang/dart_style#550] opened 2016-11-03 19:36 UTC
Given the following function:
```
void hello(String name, void stuff()) {
  print('Hello ${name}');
  stuff();
}
```

This input code should be unchanged by dartfmt.
```
void testTheFunc() {
  hello('this is a long string which has spaces in it this is a long string '
      'which has spaces in it', () {
    print('doing stuff...');
  });
}
```

Actual result:
```
void testTheFunc() {
  hello(
      'this is a long string which has spaces in it this is a long string '
      'which has spaces in it', () {
    print('doing stuff...');
  });
}
```

Another case:
```
void testTheFunc() {
  hello('this is a long string which has spaces in it this is a long string ', () {
    print('doing stuff...');
  });
}
```
gets formatted as expected:
```
void testTheFunc() {
  hello('this is a long string which has spaces in it this is a long string ',
      () {
    print('doing stuff...');
  });
}
```

**Comment by munificent** [comment] 2016-11-03 21:43
Duplicate of #133.

**Closed by munificent** 2016-11-03 21:43 UTC
