### ISSUE TITLE
Newline after =>

### ISSUE THREAD

**Issue by lukepighetti** [dart-lang/dart_style#721] opened 2018-08-10 21:23 UTC
What I prefer
```dart
_icon(Project project, context) => 
  ClickIcon(
    diameter: 56.0,
    iconUrl: project.iconUrl,
    margin: EdgeInsets.only(right: 8.0),
    linkUrl: _linkRouter(project, project.www),
    callback: _clickRouter(project, context),
    copy: !project.locked,
  );
```

What dartfmt prefers

```dart
_icon(Project project, context) => ClickIcon(
      diameter: 56.0,
      iconUrl: project.iconUrl,
      margin: EdgeInsets.only(right: 8.0),
      linkUrl: _linkRouter(project, project.www),
      callback: _clickRouter(project, context),
      copy: !project.locked,
    );
```

Is there a reason why `dartfmt` adds this newline in on multi-line arrow functions? Has this already been covered by the community somewhere? Is this a difference between Flutter use and Dart use?

**Comment by munificent** [comment] 2018-08-10 22:11
> Is there a reason why dartfmt adds this newline in on multi-line arrow functions?

Yeah, this followed the prevalent hand-formatted style that I found in the wild when first implementing the formatting rules for arrow functions. Most people seem to like it, and have for several years.

**Comment by lukepighetti** [comment] 2018-08-10 22:28
Also seen here @anders-sandholm  https://gist.github.com/anders-sandholm/b2153cdf4a541adc40c4dc50b5b6e227#file-widget-dart

**Comment by lukepighetti** [comment] 2018-08-10 22:29
How do we get this added to dartfmt?

**Comment by munificent** [comment] 2018-08-11 00:25
Yes, some of the Flutter folks aren't using dartfmt.

> How do we get this added to dartfmt?

It's not about *adding* it, it's about *changing* how it currently formats these cases. Doing that would change the formatting of a large volume of existing Dart code. Without a plan for how to manage that migration at least for code inside Google, I'm not able to make the change.

**Comment by lukepighetti** [comment] 2018-08-11 01:35
Ahh yeah I see your point. Any thoughts on how this might get handled in the future? I'm wondering if the community would benefit from a Flutter version of dartfmt?

**Comment by munificent** [comment] 2018-08-13 22:40
No, I don't know how to resolve it.

> I'm wondering if the community would benefit from a Flutter version of dartfmt?

The primary value of a formatter is having a *single* consistent style. The fact that the style happens to be good is a bonus. It's the *consistency* that offers the objective long-term value.

**Comment by lukepighetti** [comment] 2018-08-15 13:05
Hello. After spending more time with dartfmt and flutter, I think the newline after => is my biggest pain point. I believe that multiline arrow functions are best with a newline, and it seems style consistent considering that long arrow functions already newline

```dart
  /// both formatted with dartfmt
  static token() => FirebaseMessaging().getToken();
  static unsubscribe(String topic) =>
      FirebaseMessaging().unsubscribeFromTopic(topic);
```

However, as shown above, dartfmt does not newline with multi-line arrow functions, instead relying on the length of the string to determine.

I would like to present a flutter specific change that *should* not cause any problems for existing dart code.


if an arrow function returns a class, and it is multiline, put the whole class on a newline and format it like I have in my original post.

Thanks for your consideration :)

**Comment by munificent** [comment] 2018-08-15 20:40
> if an arrow function returns a class

Dartfmt doesn't know whether or not it's returning a class since it doesn't do any type analysis. But I *do* think it might be possible to say:

* If the immediate body of an `=>` expression is a method invocation, and
* The invocation's argument list has a trailing comma,

Then format it like you suggest. Looking for the trailing comma is how dartfmt switches to "Flutter-ish" style in other places, so I think it's reasonable here too. No idea when I'll have the time to implement this, but I think it's a doable change.

**Comment by lukepighetti** [comment] 2018-08-15 20:54
Question, would that mean that

```
onTap: ()=>print();
```

Would be formatted like this?

```
onTap: ()=>
  print();
```

If so, that would not be good imo.

**Comment by munificent** [comment] 2018-08-15 23:44
No, there's no reason to split on that at all since it fits on one line. Even if it does split, there's no trailing comma in the argument list, so it would split using the existing rules.

**Comment by munificent** [comment] 2024-08-02 15:54
I'm going to close this as working as intended. I've gone through a lot of code, especially in the Flutter repo, to design the new tall style and there seems to be a pretty strong preference towards keeping the initial function call on the same line as the `=>` when possible.

**Closed by munificent** 2024-08-02 15:54 UTC
Labels: common, easy, risky, meh
