### ISSUE TITLE
Bad state: No element

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dart_style#538] opened 2016-09-06 10:11 UTC
```dart
import 'package:unscripted/unscripted.dart';
import 'fhirgen.dart';

class FhirGenScriptModel extends Object with FhirGenCommand {
  @Command(
      allowTrailingOptions: true,
      help: 'Generate source code to simplify access to FHIR servers.',
      plugins: const [const Completion()])
  FhirGenScriptModel();
}

abstract class FhirGenCommand {
  @SubCommand(
      help: '''
Generate FHIR resource classes in a target project''')
  void generate(
      { //
//      @Option(
//          help: '''
//Download JSON.''',
//          abbr: 'l',
//          defaultsTo: defaultDoDownloadJson) //

      @Flag(
          help: '''
Download JSON (default is to reuse from previous download).''',
          abbr: 'l',
          defaultsTo: defaultDoDownloadJson,
          negatable: true) //
      bool doDownloadJson,
      @Flag(
          help: '''
Run "dartfmt -w ." on the target project. Caution, the whole project
will be formatted''',
          abbr: 'f',
          defaultsTo: defaultDoDartFormatTargetProject,
          negatable: true) //
      bool doDartFormatTargetProject,

}) {
runGenerator(doDownloadJson: doDownloadJson, doDartFormatTargetProject: doDartFormatTargetProject);
  }
}
```

```
 (master) $ dartfmt -w lib/bin/fhirgen_script_model.dart 
Hit a bug in the formatter when formatting lib/bin/fhirgen_script_model.dart.
Please report at: github.com/dart-lang/dart_style/issues
Bad state: No element
#0      List.last (dart:core-patch/growable_array.dart:228)
#1      SourceVisitor.visitParameterMetadata (package:dart_style/src/source_visitor.dart:1693)
#2      SourceVisitor.visitSimpleFormalParameter (package:dart_style/src/source_visitor.dart:1426)
#3      SimpleFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:8898)
#4      SourceVisitor.visit (package:dart_style/src/source_visitor.dart:1669)
#5      SourceVisitor.visitDefaultFormalParameter (package:dart_style/src/source_visitor.dart:690)
#6      DefaultFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:3390)
#7      SourceVisitor.visit (package:dart_style/src/source_visitor.dart:1669)
#8      SourceVisitor._visitTrailingCommaParameterList (package:dart_style/src/source_visitor.dart:2065)
#9      SourceVisitor.visitFormalParameterList (package:dart_style/src/source_visitor.dart:886)
#10     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4725)
#11     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:1669)
#12     SourceVisitor._visitBody (package:dart_style/src/source_visitor.dart:1865)
#13     SourceVisitor._visitMemberDeclaration (package:dart_style/src/source_visitor.dart:1818)
#14     SourceVisitor.visitMethodDeclaration (package:dart_style/src/source_visitor.dart:1279)
#15     MethodDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:7187)
#16     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:1669)
#17     SourceVisitor.visitClassDeclaration (package:dart_style/src/source_visitor.dart:438)
#18     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1847)
#19     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:1669)
#20     SourceVisitor.visitCompilationUnit (package:dart_style/src/source_visitor.dart:523)
#21     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2439)
#22     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:1669)
#23     SourceVisitor.run (package:dart_style/src/source_visitor.dart:100)
#24     DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:130)
#25     processFile (package:dart_style/src/io.dart:75)
#26     formatPaths (file:///b/build/slave/dart-sdk-linux-be/build/sdk/third_party/pkg_tested/dart_style/bin/format.dart:222)
#27     main (file:///b/build/slave/dart-sdk-linux-be/build/sdk/third_party/pkg_tested/dart_style/bin/format.dart:152)
#28     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#29     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

```
Dart VM version: 1.20.0-edge.6255638cd0623b3aa41596b98f4584876f6b8822 (Mon Sep  5 08:44:00 2016) on "linux_x64"
```

`dartfmt 0.2.9+1`

**Comment by munificent** [comment] 2016-09-07 17:56
Duplicate of #520 (which is fixed in master, but hasn't been released yet).

**Closed by munificent** 2016-09-07 17:56 UTC
