### ISSUE TITLE
Disable `dart format` for one line (or a range of lines)

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/dart_style#1242] opened 2023-07-06 06:53 UTC
This will be very helpful for, for example, Flutter repository itself. The current auto-formatter is not used by Flutter because sometimes its format makes code not very readable, and in this case, something like `// dart-format-please-ignore-the-following-line` would be very helpful.

I heard this is being worked on, but I googled and searched the issues without finding one, thus I create an issue here.

Related: https://discord.com/channels/608014603317936148/608018585025118217/1126403478424666154

**Comment by munificent** [comment] 2023-07-13 21:07
I'm not working on it yet, but, yes I've come around to the idea that this is worth doing.

**Comment by Reprevise** [comment] 2023-09-01 22:24
Came here to open an issue similar to this, I'd love to see something like this:

```dart
// formatter(ignore)
const matrixValues = [
  1, 0, 0, 0, 0,
  0, 1, 0, 0, 0,
  0, 0, 1, 0, 0,
  0, 0, 0, 1, 0
];
// formatter(end-ignore)
```

_Anyone who's worked with ColorFilter.matrix() knows the pain of the formatter putting each `double` value on a new line_

**Comment by mrcnski** [comment] 2024-01-31 13:35
```dart
print("  error: line $e.lineNum: '$e.line'");
print("         ${e.originalException.runtimeType}: ${e.originalException.toString()}");

**Comment by mrcnski** [comment] 2024-01-31 13:38
Here's another use case. `dart format` changes this:

```dart
print("  error: line $e.lineNum: '$e.line'");
print("         ${e.originalException.runtimeType}: ${e.originalException.toString()}");
```

to this:

```dart
print("  error: line $e.lineNum: '$e.line'");
print(
    "         ${e.originalException.runtimeType}: ${e.originalException.toString()}");
```

I'd like to preserve the first version, with the strings nicely lined up, to be able to see the output formatted the same way the user would see it!

**Comment by munificent** [comment] 2024-01-31 22:42
In that specific case, an easier fix is simply:

```dart
print("  error: line $e.lineNum: '$e.line'");
print("         ${e.originalException.runtimeType}: ${e.originalException}");
```

**Comment by munificent** [comment] 2024-08-03 00:30
I'm going to close this as a duplicate of #361 which I think requests the same thing.

**Closed by munificent** 2024-08-03 00:30 UTC
Labels: enhancement
