### ISSUE TITLE
dartfmt crashes on nbsp at the end of line comment

### ISSUE THREAD

**Issue by znjameswu** [dart-lang/dart_style#936] opened 2020-07-13 05:28 UTC
Using dartfmt 1.3.2

## Sample to Reproduce
```dart
void main() {
  // 
  // The above line ends with a nbsp (\u00a0)
}
```

## Crash log
```

### Request

Server was responding to request: `edit.format`

### Versions

- Visual Studio Code v1.47.0
- Dart Code v3.12.2
- Flutter SDK v1.17.5

### Analyzer Info

The analyzer was launched using the arguments:

- C:\Toolkits\dart-sdk\bin\snapshots\analysis_server.dart.snapshot
- --client-id=VS-Code
- --client-version=3.12.2

### Exception

The formatter produced unexpected output. Input was:
void main() {
  // 
  // The above line ends with a nbsp (\u00a0)
}

Which formatted to:
void main() {
  //
  // The above line ends with a nbsp (\u00a0)
}


#0      DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:158:7)
#1      EditDomainHandler.format (package:analysis_server/src/edit/edit_domain.dart:142:35)
#2      EditDomainHandler.handleRequest (package:analysis_server/src/edit/edit_domain.dart:353:16)
#3      AnalysisServer.handleRequest.<anonymous closure>.<anonymous closure> (package:analysis_server/src/analysis_server.dart:319:40)
#4      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#5      AnalysisServer.handleRequest.<anonymous closure> (package:analysis_server/src/analysis_server.dart:315:50)
#6      _rootRun (dart:async/zone.dart:1184:13)
#7      _CustomZone.run (dart:async/zone.dart:1077:19)
#8      _runZoned (dart:async/zone.dart:1619:10)
#9      runZonedGuarded (dart:async/zone.dart:1608:12)
#10     AnalysisServer.handleRequest (package:analysis_server/src/analysis_server.dart:314:5)
#11     ByteStreamServerChannel._readRequest.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:171:16)
#12     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:256:15)
#13     ByteStreamServerChannel._readRequest (package:analysis_server/src/channel/byte_stream_channel.dart:161:47)
#14     ByteStreamServerChannel.listen.<anonymous closure> (package:analysis_server/src/channel/byte_stream_channel.dart:106:26)
#15     _rootRunUnary (dart:async/zone.dart:1192:38)
#16     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#17     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#18     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#19     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#20     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#21     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#22     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#23     _LineSplitterSink._addLines (dart:convert/line_splitter.dart:152:13)
#24     _LineSplitterSink.addSlice (dart:convert/line_splitter.dart:127:5)
#25     StringConversionSinkMixin.add (dart:convert/string_conversion.dart:165:5)
#26     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#27     _rootRunUnary (dart:async/zone.dart:1192:38)
#28     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#30     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#31     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#32     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:70:11)
#33     _EventSinkWrapper.add (dart:async/stream_transformers.dart:17:11)
#34     _StringAdapterSink.add (dart:convert/string_conversion.dart:238:11)
#35     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:243:7)
#36     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:20)
#37     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:307:5)
#38     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:74:18)
#39     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:122:24)
#40     _rootRunUnary (dart:async/zone.dart:1192:38)
#41     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#42     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#43     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#44     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#45     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#46     _StreamController._add (dart:async/stream_controller.dart:655:7)
#47     _StreamController.add (dart:async/stream_controller.dart:597:5)
#48     _Socket._onData (dart:io-patch/socket_patch.dart:1982:41)
#49     _rootRunUnary (dart:async/zone.dart:1196:13)
#50     _CustomZone.runUnary (dart:async/zone.dart:1085:19)
#51     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)
#52     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#53     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:266:7)
#54     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:779:19)
#55     _StreamController._add (dart:async/stream_controller.dart:655:7)
#56     _StreamController.add (dart:async/stream_controller.dart:597:5)
#57     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1527:33)
#58     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1019:14)
#59     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#60     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#61     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#62     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```

**Comment by munificent** [comment] 2020-07-17 20:36
I think this is another special case of #901. I'll close this as a duplicate of that issue, but make sure that I handle nbsp too when I fix that.

**Closed by munificent** 2020-07-17 20:36 UTC
Labels: duplicate
