### ISSUE TITLE
Hit a bug formatting sdk_nnbd/lib/async/stream_controller.dart

### ISSUE THREAD

**Issue by cskau-g** [dart-lang/dart_style#877] opened 2019-12-02 11:30 UTC
I've encountered the following issue:
> Hit a bug in the formatter when formatting sdk_nnbd/lib/async/stream_controller.dart.
> The formatter produced unexpected output. Input was:
> [.. complete stream_controller.dart dump ..]

(See: http://gpaste/5751801267617792)

**Comment by munificent** [comment] 2019-12-02 22:34
This is a duplicate of #862, which was fixed by dartfmt 1.3.2. Are you running an older version?

**Closed by munificent** 2019-12-02 22:34 UTC

**Comment by cskau-g** [comment] 2019-12-03 07:32
> $ tools/sdks/dart-sdk/bin/dartfmt --version
> 1.3.1

Though it's a check-out from Nov 29, so not that terribly old.
Perhaps something in the SDK needs updating?

**Comment by munificent** [comment] 2019-12-05 23:17
Ah, yes. Looks like the pre-build SDK needs updating. Filed: https://github.com/dart-lang/sdk/issues/39672
