### ISSUE TITLE
Indenting .whenComplete(), etc., after a `return new Future` by four looks awkward.

### ISSUE THREAD

**Issue by tlarsen4google** [dart-lang/dart_style#253] opened 2015-05-12 09:41 UTC
When there is only a single `.whenComplete()` (or `.catchError()`, etc.) after a `new Future(...)`, `dartfmt` pulls it up to the closing parenthesis.  For example:

    test("some test", () {
        var someValue;
        return new Future(() {
            // some inline Function (closure)
        }).whenComplete(() => doSomething(someValue));
    });

But if there are multiple "dot" calls following, `dartfmt` moves them all to the next line and also indents them by 4 more columns:

    test("another test", () {
        var someValue;
        var anotherValue;
        var yetAnother;
        return new Future(() {
            // some inline Function (closure)
        })
            .whenComplete(() => doSomething(someValue))
            .whenComplete(() => doSomethingElse(anotherValue))
            .whenComplete(() => yetAnotherSometing(yetAnother));
    });

This indentation seems excessive in this case, and lining up the "dot" with the closing brace more strongly suggests that these actions follow on the `new Future()`. Something like this:

    test("another test", () {
        var someValue;
        var anotherValue;
        var yetAnother;
        return new Future(() {
            // some inline Function (closure)
        })
        .whenComplete(() => doSomething(someValue))
        .whenComplete(() => doSomethingElse(anotherValue))
        .whenComplete(() => yetAnotherSometing(yetAnother));
    });

Even if all of the items are not un-indented, at least if the first `whenComplete()` call fits, shouldn't the result have been more like the following?

    test("another test", () {
        var someValue;
        var anotherValue;
        var yetAnother;
        return new Future(() {
            // some inline Function (closure)
        }).whenComplete(() => doSomething(someValue))
            .whenComplete(() => doSomethingElse(anotherValue))
            .whenComplete(() => yetAnotherSometing(yetAnother));
    });

**Comment by munificent** [comment] 2015-06-09 21:45
Right. This is a corner of the formatter where I'm the least happy with the behavior but also the least sure what to do about it.

I definitely don't want to do your second option (put the `.` at the statement edge). It's certainly wrong at the statement level and will probably be even more confusing when this appears nested inside some larger expression.

I'm considering your last suggestion, but I don't like how it makes the first method call not line up with its siblings.

This may just be a case where there isn't a great solution. In my code, I tend to not mix `() {}` and `() =>` functions in a method chain specifically to avoid this. :neutral_face:

**Comment by tlarsen4google** [comment] 2015-06-09 22:47
I don't think I would want to write () => one-liners in the verbose () { form just to trick the formatter.

What I guess I really want is something like:

  /* pragma: dart formatter, please leave this alone */
...some code I don't want the Dart formatter to alter...
  /* endpragma: thanks for not touching my artwork */

:)

All things considered, though, I would prefer not to lose the vertical space. Too bad . and .. continuations are indented 4 columns instead of 2.

**Comment by tlarsen4google** [comment] 2015-06-11 19:43
By the way, similar tools have the off/on feature, for example, clang-format uses:

// clang-format off
... some code that does not get reformatted ...
// clang-format on

In fact, they specifically mention structured static initialization as a use case where clang-format "will never be handled perfectly". Sounds familiar.  :)

**Comment by munificent** [comment] 2015-06-11 21:16
That's certainly a possibility, but I'm trying to not rely on that crutch for as long as possible. Not having this forces me to make the formatter as good as possible. Also, it avoids users being able to sidestep presubmit requirements by just surrounding their entire file in that.

**Comment by tlarsen4google** [comment] 2015-06-11 22:14
So, more general question: where should requests to change the actual Dart style be directed? Quite a few of us wonder why . and .. continuations are indented by 4 and not just 2.

**Comment by zoechi** [comment] 2015-06-12 05:03
I didn't notice this changed (was 2 for .. previously, wasn't it? ) At first I preferred 2 but I found it weird when they were nested. I now prefer 4 because it's just more consistent.

**Comment by tlarsen4google** [comment] 2015-06-12 05:05
It just seems like a waste of horizontal space, though. I don't really see how it aids readability. The lines starting with . or .. are pretty distinct from run-of-the-mill function parameter continuations, etc.

**Comment by zoechi** [comment] 2015-06-12 07:02
Just checked it and `..` are indented just 2 spaces.

**Comment by tlarsen4google** [comment] 2015-06-12 20:11
By the way, is formatting of a function parameter like this also resulting from related dartfmt code?

     test("error", () {
        Foo fooError = new Foo.fromMap(
            baz, mockBar(), bif: mockBif, log: LOG);

        return fooError.fooParams().then((updated) {
          fail(".then() should not be executed for this test: $updated");
        },
            onError: (e) => expectFooError(
                e, 0, "Invalid foo.", "invalid_bar", LOG));
      });

onError ends up on the next line. I don't think it is so bad, but it does fall into the "consuming extra vertical space" category.

(My redactions to make the example shortened some things, so if this doesn't reproduce it, some of the fake names need to be longer.)

**Comment by munificent** [comment] 2015-06-15 20:18
Yes, that's a similar deal. It's a different corner of the formatter (method chains versus argument lists), but it's caused by the same basic formatting decision (move every ___ to the next line, even when the previous line happens to be really short).

> where should requests to change the actual Dart style be directed? Quite a few of us wonder why . and .. continuations are indented by 4 and not just 2.

You can email me directly, or on one of the main lists and I'll respond there. I'd prefer the latter since it has more visibility.

In this case, `.` is indented +4 because that's the normal indentation for wrapped expressions. Cascades are +2—even though they are wrapped expressions too—because, well, because cascades are really weird. They are an expression form but people seem to treat them as sort of like a nested block. I analyzed all of the packages on pub and most users were using +2 for their cascades, so the formatter does that.

It's annoying because it actually takes a lot of special-case code in the formatter to handle cascades being different like this. :(

**Comment by tlarsen4google** [comment] 2015-06-15 20:23
Sounds like a good reason to make all things that start with an operator (. and .. in particular) only be indented 2 columns. :)

**Comment by munificent** [comment] 2015-06-17 15:08
That would be a huge change to the world's existing code at this point. Also, indenting a wrapped expression +2 generally hurts readability because they are often followed by blocks which are +2. Consider:

```dart
if (someLongCondition
  .thatWrapsToHere()) {
  bodyThatHasSameIndent();
}
```

The reason expressions wrap +4 is to avoid those two lines having the same indentation. Personally, I think the better answer would have been to make cascades have better syntax. Barring that, they should indent +4 because they are just another operator.

**Comment by munificent** [comment] 2015-06-17 15:09
I spent some time talking to people around the office about this and the general vibe is that the behavior here is the least bad thing we can come up with, so I'm going to go ahead and close this. I agree the output isn't beautiful here, but no formatter is perfect, I suppose.

**Closed by munificent** 2015-06-17 15:09 UTC
