### ISSUE TITLE
single-line switch statements become harder to read

### ISSUE THREAD

**Issue by chipweinberger** [dart-lang/dart_style#1251] opened 2023-08-22 06:02 UTC
I'd love to turn the formatter on for my own code, but it objectively hurts carefully indented code.

Is there anyone that would actually find the *after format* more readable?

**Before format:**

```
BluetoothAdapterState _bmToBluetoothAdapterState(BmAdapterStateEnum value) {
  switch (value) {
    case BmAdapterStateEnum.unknown:      return BluetoothAdapterState.unknown;
    case BmAdapterStateEnum.unavailable:  return BluetoothAdapterState.unavailable;
    case BmAdapterStateEnum.unauthorized: return BluetoothAdapterState.unauthorized;
    case BmAdapterStateEnum.turningOn:    return BluetoothAdapterState.turningOn;
    case BmAdapterStateEnum.on:           return BluetoothAdapterState.on;
    case BmAdapterStateEnum.turningOff:   return BluetoothAdapterState.turningOff;
    case BmAdapterStateEnum.off:          return BluetoothAdapterState.off;
  }
}
```

**After format:**

```
BluetoothAdapterState _bmToBluetoothAdapterState(BmAdapterStateEnum value) {
  switch (value) {
    case BmAdapterStateEnum.unknown:
      return BluetoothAdapterState.unknown;
    case BmAdapterStateEnum.unavailable:
      return BluetoothAdapterState.unavailable;
    case BmAdapterStateEnum.unauthorized:
      return BluetoothAdapterState.unauthorized;
    case BmAdapterStateEnum.turningOn:
      return BluetoothAdapterState.turningOn;
    case BmAdapterStateEnum.on:
      return BluetoothAdapterState.on;
    case BmAdapterStateEnum.turningOff:
      return BluetoothAdapterState.turningOff;
    case BmAdapterStateEnum.off:
      return BluetoothAdapterState.off;
  }
}
```

**Comment by chipweinberger** [comment] 2023-08-22 06:07
Similar to this issue: https://github.com/dart-lang/dart_style/issues/1252

**Comment by srawlins** [comment] 2023-08-22 13:58
> Is there anyone that would actually find the after format more readable?

I more-or-less find the after format more readable, as the former format extends past 80 characters.

In my IDE, or on GitHub, or in a vertical diff, I find the former more readable, and would find it more readable even if it extended to ~100 characters. But in a side-by-side diff, I find the after format more readable, depending on my window size. Sometimes two side-by-side views at 80 characters wide barely fit, and sometimes there is room for 100 characters. Since I sometimes look at code in my IDE, sometimes at GitHub, and sometimes a side-by-side diff, the after format is the one that is least likely to soft wrap on whitespace, or extend to the right past the screen.

**Comment by chipweinberger** [comment] 2023-08-22 20:05
Appreciate your input. Yes it is a little wider than 80.

But I use a 120 character line length, and this behavior still happens.

**Comment by munificent** [comment] 2024-08-03 00:31
Closing this as a duplicate of #34.

**Closed by munificent** 2024-08-03 00:31 UTC
