### ISSUE TITLE
Align arguments if they fit

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/dart_style#152] opened 2015-01-22 21:31 UTC
main() {
      someReallyLongFunctionName('a really really really really long argument',
                                 'a really really really really long argument');
    }

becomes

    main() {
      someReallyLongFunctionName('a really really really really long argument',
          'a really really really really long argument');
    }

Either of these are acceptable for the style guide, but to me the first is better. This would only be applied after its decided where to split the lines. At that point if all the arguments would fit lined up after the function call then it would move them over, otherwise it wouldn't.

This primarily comes up on function definitions once you add in the types/etc.

**Comment by zoechi** [comment] 2015-02-19 15:48
I think this is related

```Dart
    final server = new DatastoreLocalDevServer('connect',
        workingDirectory: path.join(
            packageRoot().absolute.path, 'test/tmp_data'),
        environment: <String, String>{
      'JAVA': '/usr/lib/jvm/java-7-openjdk-amd64/bin/java'
    },
        minUpTimeBeforeShutdown: new Duration(seconds: 0));
```
should be
```Dart
    final server = new DatastoreLocalDevServer('connect',
        workingDirectory: path.join(
            packageRoot().absolute.path, 'test/tmp_data'),
        environment: <String, String>{
            'JAVA': '/usr/lib/jvm/java-7-openjdk-amd64/bin/java'},
        minUpTimeBeforeShutdown: new Duration(seconds: 0));
```
or 

```Dart
    final server = new DatastoreLocalDevServer('connect',
        workingDirectory: path.join(
            packageRoot().absolute.path, 'test/tmp_data'),
        environment: <String, String>{
            'JAVA': '/usr/lib/jvm/java-7-openjdk-amd64/bin/java'
        },
        minUpTimeBeforeShutdown: new Duration(seconds: 0));
```

**Comment by seaneagan** [comment] 2015-02-19 20:05
@zoechi I think that may actually be closer to #162.

**Comment by munificent** [comment] 2015-02-19 20:11
Yeah, I think @seaneagan is correct. Do you mind moving that comment to that bug?

Thanks!

**Comment by zoechi** [comment] 2015-02-20 08:33
Done. You're fight of course, fits better there :-)

**Comment by munificent** [comment] 2015-06-09 20:28
I'm closing this out because I don't have any plans to do this.

I agree that aligning split arguments with previous unsplit ones does look really nice in some cases. But it falls over in a lot of others.

If you have more arguments than will fit in two lines, then the formatter will split them all out into separate lines. That also—by design—causes them all to line up. But, if they fit in two lines, it just packs them in like you see here. While that's maybe suboptimal in cases where you have exactly two arguments that are related to each other and fit in exactly two lines, I don't think I want to implement any special case support for that.

Alignment in general is a rathole and I don't want go there.

**Closed by munificent** 2015-06-09 20:28 UTC

**Comment by jakemac53** [comment] 2015-06-09 20:41
Sgtm, I don't really see this style used in dart programs anyways so the existing behavior is probably more consistent with what people expect, even if I slightly prefer the other style.
