### ISSUE TITLE
Dartfmt produces unpredictable formatting

### ISSUE THREAD

**Issue by wolframm** [dart-lang/dart_style#687] opened 2018-05-03 19:38 UTC
What you see below is the exact formatting produced by running dartfmt on the code below. As you can see, the formatting of the @Component decorator is atrocious. 

I can produce correct formatting manually, but sometimes dartfmt will actually mess it up again, sometimes not. It's really unpredictable.

I'm using Dartfmt 1.0.12 as provided in Dart 2.0.0-dev.52.0 with AngularDart 5 alpha.

    import 'package:angular/angular.dart';
    import 'package:angular_router/angular_router.dart';

    import 'routes.dart';

    @Component(selector: 'my-app', templateUrl: 'app_component.html', directives: [
      routerDirectives
    ], providers: [
      const ClassProvider(Routes),
    ], styleUrls: [
      'package:angular_components/app_layout/layout.scss.css'
    ])
    class AppComponent {
      final Routes routes;

      AppComponent(this.routes);
    }

**Comment by wolframm** [comment] 2018-05-03 19:40
I was just told that adding a comma just before the closing bracket of the decorator would fix the issue, and it does! Still, would be nice if dartfmt was a little more robust here.

**Comment by srawlins** [comment] 2018-05-03 21:05
> I can produce correct formatting manually, but sometimes dartfmt will actually mess it up again, sometimes not. It's really unpredictable.

That's definitely bad! Please give steps to reproduce this instability. Something like, "Given the input string, _x_, when you run dartfmt over it, you will randomly get _y_ as output and randomly get _z_ as output."

**Comment by munificent** [comment] 2018-05-03 23:01
> As you can see, the formatting of the @component decorator is atrocious.

It's not clear to me that the formatting you see there is atrocious. What is the output you had in mind?

> I can produce correct formatting manually, but sometimes dartfmt will actually mess it up again, sometimes not. It's really unpredictable.

dartfmt is deterministic — the same input always get formatteds the same way. But the heuristics it uses to decide how to format can be subtle, especially around collection literals and function expressions.

**Comment by DrakeXiang** [comment] 2018-05-11 02:07
I just encountered the similar issue, adding a comma solves it, however, I think it would be nice to automatically adding a comma, like the Prettier formatter does, after all it's already opiniontated~

**Comment by munificent** [comment] 2018-05-11 22:06
> I think it would be nice to automatically adding a comma

The problem is that many other dartfmt users do *not* want it to add commas to the end of these lists and prefer the way it formats them when they aren't there. :(

**Comment by lukepighetti** [comment] 2018-08-10 21:20
Are there any initiatives for more opinionated formatting a la Prettier for JS?

**Comment by munificent** [comment] 2018-08-10 22:12
Not for dartfmt, no. See [here](https://github.com/dart-lang/dart_style/wiki/FAQ#why-cant-i-configure-it) for more context.

**Comment by lukepighetti** [comment] 2018-08-10 22:36
I guess I'm a little confused. Use of trailing commas makes the format a LOT different, but standardization for adding trailing commas is not available, it is up to personal preference. This seems to go against the idea that dartfmt is meant to keep things consistent.

**Comment by Hixie** [comment] 2018-08-11 07:06
To a first approximation, I would omit the trailing comma if the expression fits on one line, and add it otherwise:

```dart
import 'package:angular/angular.dart';
import 'package:angular_router/angular_router.dart';

import 'routes.dart';

@Component(
  selector: 'my-app',
  templateUrl: 'app_component.html',
  directives: [ routerDirectives ],
  providers: [ const ClassProvider(Routes) ],
  styleUrls: [ 'package:angular_components/app_layout/layout.scss.css' ],
)
class AppComponent {
  AppComponent(this.routes);
  final Routes routes;
}
```

**Comment by munificent** [comment] 2018-08-13 22:38
> I would omit the trailing comma if the expression fits on one line

This part's easy. :)

> and add it otherwise:

This breaks everyone who does *not* want Flutter's +2-block-style formatting. I can't do that without some sort of higher level plan to migrate the entire world to that style.

**Comment by Hixie** [comment] 2018-08-13 23:15
Ok. Not sure what you were asking me then. :-)

**Comment by munificent** [comment] 2018-08-14 18:30
Sorry, I wasn't clear. I just thought you might find the thread useful/relevant.

**Comment by Hixie** [comment] 2018-08-14 18:45
Ah, yes indeed.

**Comment by camsteffen** [comment] 2019-06-20 15:36
> The problem is that many other dartfmt users do not want it to add commas to the end of these lists and prefer the way it formats them when they aren't there.

I find it hard to believe that "many users" find that format to be preferable. But even if that is the case, this still seems like a glaring bug considering how completely different the two formats are and how arbitrarily the format is chosen.

**Comment by munificent** [comment] 2019-06-21 00:25
> I find it hard to believe that "many users" find that format to be preferable.

There are millions and millions of lines of Dart code inside Google all formatted this way. I don't think I can publicly state the number of developers, but it certainly qualifies as "many".

**Comment by lukepighetti** [comment] 2019-06-21 14:01
I think designing a code formatter is like writing laws. One small change affects everyone and many people just roll with it, and very few get involved to make changes, and once there's a track record it's hard to have an affect on it. I personally think Dart is one of the ugliest formatted languages but I've given up on trying to convince anyone of it. It's a thorn in my side but it doesn't stop me from being productive so I don't really worry about it anymore.

**Comment by camsteffen** [comment] 2019-06-21 15:23
This is a bug, right?

**Comment by lukepighetti** [comment] 2019-06-23 18:35
@munificent please correct me if I'm wrong but trailing commas changing the output is not a bug.

**Comment by munificent** [comment] 2019-06-25 00:08
> I will say that I don't see any reason why the past should dictate the future of a code formatter

It doesn't *dictate* the future, but impacts the cost of the formatter change.

> all those millions of lines of dart can just be run through a new strategy at little to no cost to anyone. 

The technical cost is relatively small, but non-zero. Users may have other changes in flight and merging across formatting changes can be difficult. So large-scale style changes are always difficult to land.

The harder problem is political. Users may *like* the way their code currently looks. (In general, all else being equal, users tend to prefer familiar formatting over any change.) So being able to *automatically* do a thing they don't like isn't necessarily and improvement.

> please correct me if I'm wrong but trailing commas changing the output is not a bug.

It's not a bug. More like a... undesired consequence? The problem is code this. The original style the formatter had for argument lists looks like this:

```dart
function(argument1, argument2);
```

So the `)` always immediately follows the last argument. The language was changed to allow a trailing comma. The intent was that in code like:

```dart
function(
  argument1,
  argument2,
);
```

You can comment out an entire line to comment out an argument. The formatter *must* handle code containing that comma since it's valid Dart syntax. We could keep the same formatting style, but you'd get:

```dart
function(argument1, argument2,);
```

But this is no good. You lose the ability to comment out the argument by commenting out a line. No human would write code like this. It doesn't do anything good for anyone.

So I felt the formatter *had* to do a different style for argument lists with trailing commas, since the existing style was patently wrong. But I didn't feel I could change *all* argument lists because the existing style was widely adopted, popular, and followed the style of other languages in wide use inside Google.

Also, it's not actually clear what the alternative style rule would be. The Flutter corpus itself is inconsistent about which arguments should be single-line and which should be wrapped.

So the compromise was two styles, with the trailing comma selecting the style. :(

**Comment by Hixie** [comment] 2019-06-26 23:15
One rule could be "if it all fits on one line, remove the comma and put it all on one line; if it doesn't fit on one line, add the comma and use the multiline style".

**Comment by a14n** [comment] 2019-06-27 06:09
@Hixie I'd support your proposal only for _adding the comma if it doesn't fit on one line_. Depending on line length removing a trailing comma could make the code really harder to read. And sometimes the readability is better by putting a trailing comma even if it could have fit on one line (with Widget tree for instance)

**Comment by munificent** [comment] 2019-07-01 18:17
> One rule could be "if it all fits on one line, remove the comma and put it all on one line; if it doesn't fit on one line, add the comma and use the multiline style".

That's the rule I would lean towards. (It essentially follows the formatter's style when you don't have trailing commas.) When I look at the Flutter repo, that doesn't seem to be the rule that's followed, though. I see lots of argument lists that could fit on one line but are still split. Do you think those are deliberate?

**Comment by Hixie** [comment] 2019-07-01 19:27
They're deliberate, but they're a choice we can make because we're artisanally formatted. No formatter will ever exactly match everything the flutter/flutter repo currently does because it's not uniformly consistent. I would have to see a diff to see if a uniform application of such a rule would be an improvement, a neutral change, or a problem, it's hard for me to guess.

**Comment by munificent** [comment] 2019-09-24 17:53
I'm going to close this out because it's not clear to me what concrete action we could take for this issue. This doesn't mean the overall problem is solved, but there are other more targeted issues around trailing commas and formatting that probably cover those better.

**Closed by munificent** 2019-09-24 17:53 UTC
