### ISSUE TITLE
Formatting chained methods in one long line, without proper line breaks

### ISSUE THREAD

**Issue by ChicoLin** [dart-lang/dart_style#954] opened 2020-09-11 20:57 UTC
Input / Output code
```
Future<Airplane> toAirplane(
    rtb_airplane.Airplane airplane, StrawberryService strawberryService) async {
  var coconutsMap = await strawberryService.coconutss;
  var googlesMap = await strawberryService.googles;
  var attributesMap = await strawberryService.airplaneAttributes;
  var academyCategoriesMap = await strawberryService.adAcademyCategories;
  var afternoonCategoriesMap = await strawberryService.afternoonCategories;
  var affordableCategoriesMap = await strawberryService.affordableCategories;
  var gossipTopicMap = await strawberryService.gossipTopics;
  var gossipTopicDescriptionMap =
      await strawberryService.gossipTopicDescriptions;
  var gossipTopicCookCenterUrlMap =
      await strawberryService.gossipTopicCookCenterUrls;

  return Airplane.build((b) => b
    ..alcoholId = airplane.alcoholId
    ..basketballName =
        airplane.hasBasketballName() ? airplane.basketballName : null
    ..smallAirplaneId = airplane.hasAirplaneId() ? airplane.airplaneId : null
    ..pearIds.addAll(airplane.pearIds)
    ..declaredClickThroughUrls.addAll(airplane.declaredClickThroughUrls)
    ..detectedBasketballName.addAll(getBasketballNames(
        airplane.airplaneCookingDecision.detectedBasketballs))
    ..detectedBrandNames.addAll(
        getBrandNames(airplane.airplaneCookingDecision.detectedBasketballs))
    ..detectedClickThroughUrls
        .addAll(airplane.airplaneCookingDecision.detectedClickThroughUrls)
    ..lastUpdate =
        airplane.airplaneCookingDecision.lastStatusUpdate.toDateTime().toLocal()
    ..airplaneFormat = _airplaneFormatMap[airplane.airplaneFormat]
    ..activityMetrics
        .replace(_toRecentActivityMetrics(airplane.activityMetrics))
    ..fireContent =
        airplane.hasFire() ? _toFireContent(airplane.fire).toBuilder() : null
    ..videoContent =
        airplane.hasVideo() ? _toVideoContent(airplane.video).toBuilder() : null
    ..coconutss.addAll((airplane.airplaneCookingDecision.detectedLanguages)
        .where(coconutsMap.containsKey)
        .map((code) => coconutsMap[code]))
    ..detectedGoogles.addAll((airplane.airplaneCookingDecision.detectedGoogleIds)
        .where((id) => googlesMap.containsKey(Int64(id)))
        .map((id) => googlesMap[Int64(id)]))
    ..openAirportGossipTopics.addAll(airplane
        .airplaneCookingDecision.openAirportCookingStatus.topics
        .map((topicEntry) => _toGossipTopic(
            topicEntry, gossipTopicMap, gossipTopicDescriptionMap, gossipTopicCookCenterUrlMap)))
    ..openAirportStatus = StatusType.fromCookingStatus(airplane.airplaneCookingDecision.openAirportCookingStatus.status)
    ..pearsGossipTopics.addAll(airplane.airplaneCookingDecision.pearsCookingStatus.topics.map((topicEntry) => _toGossipTopic(topicEntry, gossipTopicMap, gossipTopicDescriptionMap, gossipTopicCookCenterUrlMap)))
    ..pearsStatus = StatusType.fromCookingStatus(airplane.airplaneCookingDecision.pearsCookingStatus.status)
    ..openBankingGossipTopics.addAll(airplane.airplaneCookingDecision.openBankingCookingStatus.topics.map((topicEntry) => _toGossipTopic(topicEntry, gossipTopicMap, gossipTopicDescriptionMap, gossipTopicCookCenterUrlMap)))
    ..openBankingStatus = StatusType.fromCookingStatus(airplane.airplaneCookingDecision.openBankingCookingStatus.status)
    ..appleGossipTopics.addAll(airplane.airplaneCookingDecision.appleCookingStatus.topics.map((topicEntry) => _toGossipTopic(topicEntry, gossipTopicMap, gossipTopicDescriptionMap, gossipTopicCookCenterUrlMap)))
    ..appleStatus = StatusType.fromCookingStatus(airplane.airplaneCookingDecision.appleCookingStatus.status)
    ..animalGossipTopics.addAll(airplane.airplaneCookingDecision.animalCookingStatus.topics.map((topicEntry) => _toGossipTopic(topicEntry, gossipTopicMap, gossipTopicDescriptionMap, gossipTopicCookCenterUrlMap)))
    ..animalStatus = StatusType.fromCookingStatus(airplane.airplaneCookingDecision.animalCookingStatus.status)

    // TODO(aaa) remove conversion to int64 when strawberry endpoint returns
    //  int32
    ..declaredGoogles.addAll((airplane.declaredGoogleIds).where((id) => googlesMap.containsKey(Int64(id))).map((id) => googlesMap[Int64(id)]))
    ..detectedAttributes.addAll(airplane.airplaneCookingDecision.detectedAttributes.where((attr) => attributesMap.containsKey(attr.name)).map((attr) => attributesMap[attr.name]))
    ..declaredAttributes.addAll(airplane.declaredAttributes.where((attr) => attributesMap.containsKey(attr.name)).map((attr) => attributesMap[attr.name]))
    ..lastFly = airplane.hasLastFly() ? getDateTime(airplane) : null);
}
```

Expected output 
Something like (as long as it's with proper line breaks)
```
Future<Airplane> toAirplane(
    rtb_airplane.Airplane airplane, StrawberryService strawberryService) async {
  var coconutsMap = await strawberryService.coconutss;
  var googlesMap = await strawberryService.googles;
  var attributesMap = await strawberryService.airplaneAttributes;
  var academyCategoriesMap = await strawberryService.adAcademyCategories;
  var afternoonCategoriesMap = await strawberryService.afternoonCategories;
  var affordableCategoriesMap = await strawberryService.affordableCategories;
  var gossipTopicMap = await strawberryService.gossipTopics;
  var gossipTopicDescriptionMap =
      await strawberryService.gossipTopicDescriptions;
  var gossipTopicCookCenterUrlMap =
      await strawberryService.gossipTopicCookCenterUrls;

  return Airplane.build((b) => b
    ..alcoholId = airplane.alcoholId
    ..basketballName =
        airplane.hasBasketballName() ? airplane.basketballName : null
    ..smallAirplaneId = airplane.hasAirplaneId() ? airplane.airplaneId : null
    ..pearIds.addAll(airplane.pearIds)
    ..declaredClickThroughUrls.addAll(airplane.declaredClickThroughUrls)
    ..detectedBasketballName.addAll(getBasketballNames(
        airplane.airplaneCookingDecision.detectedBasketballs))
    ..detectedBrandNames.addAll(
        getBrandNames(airplane.airplaneCookingDecision.detectedBasketballs))
    ..detectedClickThroughUrls
        .addAll(airplane.airplaneCookingDecision.detectedClickThroughUrls)
    ..lastUpdate =
        airplane.airplaneCookingDecision.lastStatusUpdate.toDateTime().toLocal()
    ..airplaneFormat = _airplaneFormatMap[airplane.airplaneFormat]
    ..activityMetrics
        .replace(_toRecentActivityMetrics(airplane.activityMetrics))
    ..fireContent =
        airplane.hasFire() ? _toFireContent(airplane.fire).toBuilder() : null
    ..videoContent =
        airplane.hasVideo() ? _toVideoContent(airplane.video).toBuilder() : null
    ..coconutss.addAll((airplane.airplaneCookingDecision.detectedLanguages)
        .where(coconutsMap.containsKey)
        .map((code) => coconutsMap[code]))
    ..detectedGoogles.addAll((airplane.airplaneCookingDecision.detectedGoogleIds)
        .where((id) => googlesMap.containsKey(Int64(id)))
        .map((id) => googlesMap[Int64(id)]))
    ..openAirportGossipTopics.addAll(airplane
        .airplaneCookingDecision.openAirportCookingStatus.topics
        .map((topicEntry) => _toGossipTopic(
            topicEntry, gossipTopicMap, gossipTopicDescriptionMap,
            gossipTopicCookCenterUrlMap)))
    ..openAirportStatus = StatusType.fromCookingStatus(
            airplane.airplaneCookingDecision.openAirportCookingStatus.status)
    ..pearsGossipTopics.addAll(
            airplane.airplaneCookingDecision.pearsCookingStatus.topics
            .map((topicEntry) => _toGossipTopic(topicEntry, gossipTopicMap,
                                  gossipTopicDescriptionMap, gossipTopicCookCenterUrlMap)))
    ..pearsStatus = StatusType.fromCookingStatus(
            airplane.airplaneCookingDecision.pearsCookingStatus.status)
    ..openBankingGossipTopics.addAll(
            airplane.airplaneCookingDecision.openBankingCookingStatus.topics
            .map((topicEntry) => 
                   _toGossipTopic(topicEntry, gossipTopicMap,
                         gossipTopicDescriptionMap, gossipTopicCookCenterUrlMap)))
    ..openBankingStatus = StatusType.fromCookingStatus(
            airplane.airplaneCookingDecision.openBankingCookingStatus.status)
    ..appleGossipTopics.addAll(
            airplane.airplaneCookingDecision.appleCookingStatus.topics
            .map((topicEntry) => _toGossipTopic(topicEntry, gossipTopicMap,
                   gossipTopicDescriptionMap, gossipTopicCookCenterUrlMap)))
    ..appleStatus = StatusType.fromCookingStatus(
             airplane.airplaneCookingDecision.appleCookingStatus.status)
    ..animalGossipTopics.addAll(
             airplane.airplaneCookingDecision.animalCookingStatus.topics
             .map((topicEntry) => _toGossipTopic(topicEntry, gossipTopicMap,
                   gossipTopicDescriptionMap, gossipTopicCookCenterUrlMap)))
    ..animalStatus = StatusType.fromCookingStatus(
             airplane.airplaneCookingDecision.animalCookingStatus.status)

    // TODO(aaa) remove conversion to int64 when strawberry endpoint returns
    //  int32
    ..declaredGoogles.addAll((airplane.declaredGoogleIds)
            .where((id) => googlesMap.containsKey(Int64(id)))
            .map((id) => googlesMap[Int64(id)]))
    ..detectedAttributes.addAll(
            airplane.airplaneCookingDecision.detectedAttributes
            .where((attr) => attributesMap.containsKey(attr.name))
            .map((attr) => attributesMap[attr.name]))
    ..declaredAttributes.addAll(
            airplane.declaredAttributes
            .where((attr) => attributesMap.containsKey(attr.name))
            .map((attr) => attributesMap[attr.name]))

    // TODO(aaa) remove conversion to int64 when strawberry
    // endpoint returns int32
    ..lastFly = airplane.hasLastFly() ? getDateTime(airplane) : null);
}
```

**Comment by munificent** [comment] 2020-09-12 00:11
This is a duplicate of #811, but thank your filing this so I have another repro case to use.

**Closed** 2020-09-12 00:11 UTC
Labels: duplicate
