### ISSUE TITLE
Issue with Dart Analyzer. Got this error when formatting my dart code

### ISSUE THREAD

**Issue by blackcat91** [dart-lang/dart_style#1007] opened 2021-03-10 18:33 UTC
Hello,
The following error was generated when trying to format my dart code. Recently, I have been having problems with the dart analyzer. It just stopped working randomly. Recently, I updated dart and flutter.

This is the error form the formatter.

`Null check operator used on a null value
#0      Parser._attemptPrecedenceLevelRecovery (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4901:77)
#1      Parser._parsePrecedenceExpressionLoop (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4874:13)
#2      Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4754:12)
#3      Parser._parsePrecedenceExpressionLoop (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4785:17)
#4      Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4754:12)
#5      Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4680:13)
#6      Parser.parseExpressionStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4645:13)
#7      Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6324:16)
#8      Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4441:14)
#9      Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4431:20)
#10     Parser.parseBlock (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6717:15)
#11     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4452:14)
#12     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4431:20)
#13     Parser.parseIfStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6415:13)
#14     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4468:14)
#15     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4431:20)
#16     Parser.parseIfStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6421:15)
#17     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4468:14)
#18     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4431:20)
#19     Parser.parseIfStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6421:15)
#20     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4468:14)
#21     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4431:20)
#22     Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4336:15)
#23     Parser.parseAsyncOptBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4164:13)
#24     Parser.parseFunctionExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4093:13)
#25     Parser.parseParenthesizedExpressionOrFunctionLiteral (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5282:18)
#26     Parser.parsePrimary (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5249:14)
#27     Parser.parseUnaryExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5115:12)
#28     Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4739:13)
#29     Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4680:13)
#30     Parser.parseArgumentsRest (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5984:15)
#31     Parser.parseArguments (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5956:12)
#32     Parser.parseArgumentsOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5937:14)
#33     Parser.parseSend (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5916:13)
#34     Parser.parseSendOrFunctionLiteral (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5643:12)
#35     Parser.parsePrimary (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5208:14)
#36     Parser._parsePrecedenceExpressionLoop (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4804:21)
#37     Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4754:12)
#38     Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4680:13)
#39     Parser.parseExpressionStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4645:13)
#40     Parser.parseExpressionStatementOrDeclarationAfterModifiers (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6324:16)
#41     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4441:14)
#42     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4431:20)
#43     Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4336:15)
#44     Parser.parseAsyncOptBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4164:13)
#45     Parser.parseFunctionExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4093:13)
#46     Parser.parseParenthesizedExpressionOrFunctionLiteral (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5277:16)
#47     Parser.parsePrimary (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5249:14)
#48     Parser.parseUnaryExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5115:12)
#49     Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4739:13)
#50     Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4680:13)
#51     Parser.parseArgumentsRest (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5984:15)
#52     Parser.parseArguments (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5956:12)
#53     Parser.parseArgumentsOpt (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5937:14)
#54     Parser.parseSend (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5916:13)
#55     Parser.parseSendOrFunctionLiteral (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5643:12)
#56     Parser.parsePrimary (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5208:14)
#57     Parser._parsePrecedenceExpressionLoop (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4804:21)
#58     Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4754:12)
#59     Parser.parseAwaitExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:6809:13)
#60     Parser.parseUnaryExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:5068:14)
#61     Parser.parsePrecedenceExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4739:13)
#62     Parser.parseExpression (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4680:13)
#63     Parser.parseExpressionStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4645:13)
#64     Parser.parseStatementX (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4526:14)
#65     Parser.parseStatement (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4431:20)
#66     Parser.parseFunctionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:4336:15)
#67     Parser.parseMethod (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3865:15)
#68     Parser.parseClassOrMixinOrExtensionMemberImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3684:15)
#69     Parser.parseClassOrMixinOrExtensionBody (package:_fe_analyzer_shared/src/parser/parser_impl.dart:3343:15)
#70     Parser.parseClass (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1964:13)
#71     Parser.parseClassOrNamedMixinApplication (package:_fe_analyzer_shared/src/parser/parser_impl.dart:1922:14)
#72     Parser.parseTopLevelKeywordDeclaration (package:_fe_analyzer_shared/src/parser/parser_impl.dart:581:14)
#73     Parser.parseTopLevelDeclarationImpl (package:_fe_analyzer_shared/src/parser/parser_impl.dart:477:14)
#74     Parser.parseUnit (package:_fe_analyzer_shared/src/parser/parser_impl.dart:357:15)
#75     Parser.parseCompilationUnit2 (package:analyzer/src/generated/parser.dart:199:32)
#76     Parser.parseCompilationUnit (package:analyzer/src/generated/parser.dart:195:12)
#77     parseString (package:analyzer/dart/analysis/utilities.dart:94:21)
#78     DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:115:23)
#79     processFile (package:dart_style/src/io.dart:142:28)
#80     processDirectory (package:dart_style/src/io.dart:123:10)
#81     formatPaths (package:dart_style/src/io.dart:61:12)
#82     main (file:///C:/b/s/w/ir/cache/builder/src/third_party/dart/third_party/pkg_tested/dart_style/bin/format.dart:141:5)
#83     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:281:32)
#84     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)`

This is the error I get from the analyzer:

`Dart Code extension: 3.20.1
Flutter extension: 3.20.0 (activated)

App: Visual Studio Code
Version: 1.54.1
Platform: win

Workspace type: Flutter
Analyzer type: DAS
Multi-root?: false

Dart SDK:
    Loc: C:\src\flutter\bin\cache\dart-sdk
    Ver: 2.12.0
Flutter SDK:
    Loc: C:\src\flutter
    Ver: 2.0.1

[10:31:35 AM] [Analyzer] [Info] <== {"event":"analysis.errors","params":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\main.dart","errors":[{"severity":"INFO","type":"HINT","location":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\main.dart","offset":4572,"length":15,"startLine":117,"startColumn":8},"message":"The value of the field '_isCreatingLink' isn't used.","correction":"Try removing the field, or using it.","code":"unused_field","url":"https://dart.dev/tools/diagnostic-messages#unused…
[10:31:35 AM] [Analyzer] [Info] <== {"event":"analysis.occurrences","params":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\main.dart","occurrences":[{"element":{"kind":"PREFIX","name":"tz","location":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\main.dart","offset":626,"length":2,"startLine":11,"startColumn":47},"flags":0},"offsets":[626,674],"length":2},{"element":{"kind":"CLASS","name":"Future","location":{"file":"C:\\src\\flutter\\bin\\cache\\pkg\\sky_engine\\lib\\async\\future.dart","o…
[10:31:35 AM] [Analyzer] [Info] <== {"event":"analysis.closingLabels","params":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\main.dart","labels":[{"offset":3393,"length":892,"label":"MaterialApp"},{"offset":3605,"length":672,"label":"ThemeData"},{"offset":4866,"length":87,"label":"BottomNavigationBarItem"},{"offset":6007,"length":394,"label":"NotificationDetails"},{"offset":6052,"length":333,"label":"AndroidNotificationDetails"},{"offset":7290,"length":863,"label":"StreamBuilder"},{"offset":7607,"length":471…
[10:31:35 AM] [Analyzer] [Info] <== {"event":"analysis.folding","params":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\main.dart","regions":[{"kind":"FUNCTION_BODY","offset":1213,"length":271},{"kind":"INVOCATION","offset":1629,"length":186},{"kind":"FUNCTION_BODY","offset":2018,"length":1216},{"kind":"INVOCATION","offset":2174,"length":157},{"kind":"INVOCATION","offset":3066,"length":58},{"kind":"CLASS_BODY","offset":3276,"length":1017},{"kind":"FUNCTION_BODY","offset":3380,"length":910},{"kind":"INVOCATION…
[10:31:35 AM] [Analyzer] [Info] <== {"event":"analysis.outline","params":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\main.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit>","location":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\main.dart","offset":0,"length":8164,"startLine":1,"startColumn":1},"flags":0},"offset":0,"length":8164,"codeOffset":0,"codeLength":8164,"children":[{"element":{"kind":"FUNCTION","name":"_firebaseMessagingBackgroundHandler","lo…
[10:31:35 AM] [Analyzer] [Info] <== {"event":"flutter.outline","params":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\main.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":8164,"codeOffset":0,"codeLength":8164,"dartElement":{"kind":"COMPILATION_UNIT","name":"<unit>","location":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\main.dart","offset":0,"length":8164,"startLine":1,"startColumn":1},"flags":0},"children":[{"kind":"DART_ELEMENT","offset":1047,"length":438,"codeOffset":1134,"c…
[10:31:35 AM] [Analyzer] [Info] <== {"event":"analysis.errors","params":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\models\\room_model.dart","errors":[]}}
[10:31:35 AM] [Analyzer] [Info] <== {"event":"analysis.occurrences","params":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\models\\room_model.dart","occurrences":[{"element":{"kind":"CLASS","name":"RoomModel","location":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\models\\room_model.dart","offset":64,"length":9,"startLine":3,"startColumn":7},"flags":0},"offsets":[64,320],"length":9},{"element":{"kind":"CLASS","name":"String","location":{"file":"C:\\src\\flutter\\bin\\cache\\pkg\\sky_engin…
[10:31:35 AM] [Analyzer] [Info] <== {"event":"analysis.closingLabels","params":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\models\\room_model.dart","labels":[]}}
[10:31:35 AM] [Analyzer] [Info] <== {"event":"analysis.folding","params":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\models\\room_model.dart","regions":[{"kind":"CLASS_BODY","offset":75,"length":649},{"kind":"FUNCTION_BODY","offset":337,"length":384},{"kind":"CLASS_BODY","offset":742,"length":899},{"kind":"FUNCTION_BODY","offset":1177,"length":461},{"kind":"CLASS_BODY","offset":1659,"length":127},{"kind":"FUNCTION_BODY","offset":1725,"length":58}]}}
[10:31:35 AM] [Analyzer] [Info] <== {"event":"analysis.outline","params":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\models\\room_model.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit>","location":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\models\\room_model.dart","offset":0,"length":1789,"startLine":1,"startColumn":1},"flags":0},"offset":0,"length":1789,"codeOffset":0,"codeLength":1789,"children":[{"element":{"kind":"CLASS","name":"RoomModel","loc…
[10:31:35 AM] [Analyzer] [Info] <== {"event":"flutter.outline","params":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\models\\room_model.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":1789,"codeOffset":0,"codeLength":1789,"dartElement":{"kind":"COMPILATION_UNIT","name":"<unit>","location":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\models\\room_model.dart","offset":0,"length":1789,"startLine":1,"startColumn":1},"flags":0},"children":[{"kind":"DART_ELEMENT","offset":58,"length…
[10:31:35 AM] [Analyzer] [Info] <== {"event":"analysis.errors","params":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\resources\\user.dart","errors":[{"severity":"ERROR","type":"SYNTACTIC_ERROR","location":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\resources\\user.dart","offset":1948,"length":3,"startLine":1,"startColumn":1949},"message":"Expected to find ')'.","code":"expected_token","hasFix":true}]}}
[10:31:35 AM] [Analyzer] [Info] <== {"event":"analysis.occurrences","params":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\resources\\user.dart","occurrences":[]}}
[10:31:35 AM] [Analyzer] [Info] <== {"event":"analysis.closingLabels","params":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\resources\\user.dart","labels":[]}}
[10:31:35 AM] [Analyzer] [Info] <== {"event":"analysis.folding","params":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\resources\\user.dart","regions":[]}}
[10:31:35 AM] [Analyzer] [Info] <== {"event":"analysis.outline","params":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\resources\\user.dart","kind":"LIBRARY","outline":{"element":{"kind":"COMPILATION_UNIT","name":"<unit>","location":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\resources\\user.dart","offset":0,"length":0,"startLine":1,"startColumn":1},"flags":0},"offset":0,"length":0,"codeOffset":0,"codeLength":0}}}
[10:31:35 AM] [Analyzer] [Info] <== {"event":"flutter.outline","params":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\resources\\user.dart","outline":{"kind":"DART_ELEMENT","offset":0,"length":0,"codeOffset":0,"codeLength":0,"dartElement":{"kind":"COMPILATION_UNIT","name":"<unit>","location":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\resources\\user.dart","offset":0,"length":0,"startLine":1,"startColumn":1},"flags":0}}}}
[10:31:35 AM] [Analyzer] [Error] Unhandled exception:
Null c
[10:31:35 AM] [Analyzer] [Error] heck operator used on a null value
#0      Driver._captureExceptions.errorFunction (package:analysis_server/src/server/driver.dart:480:7)
#1      _CustomZone.handleUncaughtError (dart:async/zone.dart:1241:19)
#2      _CustomZone.runGuarded (dart:async/zone.dart:1164:7)
#3      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1202:23)
#4      _microtaskLoop (dart:async
[10:31:35 AM] [Analyzer] [Error] /schedule_microtask.dart:40:21)
#5      _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#6      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:120:13)
#7      _Timer._runTimers (dart:isolate-pat
[10:31:35 AM] [Analyzer] [Error] ch/timer_impl.dart:402:11)
#8      _Timer._handleMessage (dart:isolate-patch/timer_impl.dar
[10:31:35 AM] [Analyzer] [Error] t:426:5)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
[10:31:35 AM] [Analyzer] [Info] ==> {"id":"17","method":"edit.getFixes","params":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\resources\\user.dart","offset":7270},"clientRequestTime":1615401095919}
[10:31:35 AM] [Analyzer] [Info] ==> {"id":"18","method":"edit.getAssists","params":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\resources\\user.dart","length":5,"offset":7265},"clientRequestTime":1615401095919}
[10:31:35 AM] [Analyzer] [Info] ==> {"id":"19","method":"edit.getAvailableRefactorings","params":{"file":"C:\\Users\\brand\\Documents\\Projects\\greenthumb\\lib\\resources\\user.dart","length":5,"offset":7265},"clientRequestTime":1615401095919}
[10:31:36 AM] [Analyzer] [Info] Process terminated! 255, null`

With these errors I can't run my app. Please help

**Comment by natebosch** [comment] 2021-03-24 17:45
cc @scheglov 

The mentioned line was changed during the null safety migration. The line still exists but it was moved some.

https://github.com/dart-lang/sdk/blob/72c1995001d1214138a8186032f2199f237bc505/pkg/_fe_analyzer_shared/lib/src/parser/parser_impl.dart#L4901

@blackcat91 - does this still happen? Can you consistently reproduce it? Can you share an example source input that causes dartfmt to crash?

**Comment by scheglov** [comment] 2021-03-25 20:00
Looks as duplicate of https://github.com/dart-lang/sdk/issues/45327 fixed recently.

**Comment by munificent** [comment] 2021-03-30 00:22
Closing as duplicate.

**Closed by munificent** 2021-03-30 00:22 UTC
