### ISSUE TITLE
typedefs for generic functions break interestingly

### ISSUE THREAD

**Issue by floitschG** [dart-lang/dart_style#629] opened 2017-05-17 11:16 UTC
I just ran the formatter over my `zone.dart` files, and it broke the line *before* the equal sign:

``` dart
typedef HandleUncaughtErrorHandler
    = R Function<R>(Zone self, ZoneDelegate parent, Zone zone, Object error,
        StackTrace stackTrace);
typedef RunHandler
    = R Function<R>(Zone self, ZoneDelegate parent, Zone zone, R Function() f);
typedef RunUnaryHandler
    = R Function<R, T>(
        Zone self, ZoneDelegate parent, Zone zone, R Function(T arg) f, T arg);
typedef RunBinaryHandler
    = R Function<R, T1, T2>(Zone self, ZoneDelegate parent, Zone zone,
        R Function(T1 arg1, T2 arg2) f, T1 arg1, T2 arg2);
typedef RegisterCallbackHandler
    = ZoneCallback<R> Function<R>(
        Zone self, ZoneDelegate parent, Zone zone, R Function() f);
typedef RegisterUnaryCallbackHandler
    = ZoneUnaryCallback<R, T> Function<R, T>(
        Zone self, ZoneDelegate parent, Zone zone, R Function(T arg) f);
typedef RegisterBinaryCallbackHandler
    = ZoneBinaryCallback<R, T1, T2> Function<R, T1, T2>(Zone self,
        ZoneDelegate parent, Zone zone, R Function(T1 arg1, T2 arg2) f);
```

I have never seen us break lines this way.
(dartfmt that comes with the sdk).

**Comment by munificent** [comment] 2017-05-17 20:10
This is using the prebuilt dartfmt that is checked into the repo, right? If so, this is a duplicate of #627. That snapshot is out of date with the latest dartfmt.

cc @whesse

**Closed by munificent** 2017-05-17 20:10 UTC
