### ISSUE TITLE
should avoid breaking indexer access if possible

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dart_style#160] opened 2015-02-03 19:58 UTC
```diff
-  factory ResultSet.fromJson(Map json) => new ResultSet(json['platform'],
-      json['release'],
+  factory ResultSet.fromJson(Map json) => new ResultSet(json['platform'], json[
+      'release'],
       json['results'].map((result) => new Result.fromJson(result)).toList());
```

This feels like a regression

**Comment by munificent** [comment] 2015-02-03 21:26
Dupe of #158.

**Closed by munificent** 2015-02-03 21:26 UTC
Labels: duplicate
