### ISSUE TITLE
Unexpectedly formatting in new style

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/dart_style#1617] opened 2024-12-06 23:50 UTC
Given the following setup:

`myproject/pubspec.yaml`:
```yaml
name: test
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
```

`myproject/lib/foo.dart`:
```dart
enum foo {
  entry1,
  entry2,
}
```

I would have expected that running `dart format .` in the `myproject` directory formats `foo.dart` in the old style without removing/adding any trailing commas because the lower SDK bound in the `pubspec.yaml` is below 3.7. However, it actually uses the new format style and removes the trailing comma:

```dart
enum foo { entry1, entry2 }
```

Observation: After running `dart pub update` the formatter actually respects the given sdk constraints and uses the old style:

```dart
enum foo {
  entry1,
  entry2,
}
```

This caused an actual breakage in flutter's assets-for-api-docs repository where the CI was all of the sudden (without bumping the lower SDK constraints) expecting everything to be formatted in the new style: https://github.com/flutter/assets-for-api-docs/actions/runs/11847189657/job/33016375039

Expectation: The formatter uses the correct style based on the sdk constrains in the pubspec.yaml even if `dart pub update` hasn't been run to avoid breaking CI this way.

I observed this behavior with the formatter from Dart SDK version 3.7.0-219.0.dev.

If it doesn't reproduce: delete the `.dart_tools` directory and `pubpsec.lock` file.

**Comment by goderbauer** [comment] 2024-12-06 23:51
cc @piinks, who noticed this breakage
cc @munificent

**Comment by munificent** [comment] 2024-12-07 01:30
Oof, yeah, this is a nasty UX pitfall. I'm going to close this as a duplicate of #1597 which has a lot more context.

Sorry for the breakage. I'm still trying to figure out the best way for the formatter to help users avoid this problem without adding unbounded complexity to how it interacts with the file system.

**Closed by munificent** 2024-12-07 01:30 UTC
