### ISSUE TITLE
trailing commas should be automatically added where necessary to avoid incorrect indentation

### ISSUE THREAD

**Issue by DetachHead** [dart-lang/dart_style#1104] opened 2022-03-25 13:27 UTC
from #1100:
> ### code
> ```dart
> void foo({String? value, int? value2}) {}
> 
> String bar(String value) => "";
> 
> void main() {
>   return foo(
>     value: bar(
>       "",
>     )
>   );
> }
> ```
> 
> ### actual result
> ```dart
> void foo({String? value, int? value2}) {}
> 
> String bar(String value) => "";
> 
> void main() {
>   return foo(
>       value: bar(
>     "",
>   ));
> }
> ```
> 
> ### expected result
> it could instead add the missing trailing comma so that it gets formatted correctly:
> 
> ```dart
> void main() {
>   return foo(
>     value: bar(
>       "",
>     ),
>   );
> }
> ```
> 
> ### irl example
> this also screws up the tree lines in the flutter intellij plugin:
> 
> ```dart
> class _State extends State<MyHomePage> {
>   @override
>   Widget build(BuildContext context) {
>     return GestureDetector(
>         child: Row(
>       children: const [Text("Foo")],
>     ));
>   }
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/57028336/156906359-275d0de6-d418-4228-b083-ac43268f7384.png)

**Comment by srawlins** [comment] 2022-03-25 14:29
Duplicate of https://github.com/dart-lang/dart_style/issues/753?

**Closed** 2022-03-25 15:17 UTC
