### ISSUE TITLE
String moved to newline

### ISSUE THREAD

**Issue by kegluneq** [dart-lang/dart_style#423] opened 2015-09-15 20:54 UTC
Input:
```
void allTests() {
  describe('inliner', () {
    it('should inline `templateUrl` and `styleUrls` values expressed as '
       'absolute urls.', () async {
    });
  });
}
```

Output:
```
void allTests() {
  describe('inliner', () {
    it(
        'should inline `templateUrl` and `styleUrls` values expressed as '
        'absolute urls.', () async {});
  });
}
```

I wouldn't expect the text after `it(` to be moved to the next line.

**Comment by munificent** [comment] 2015-11-05 23:53
Duplicate of #409.

**Closed by munificent** 2015-11-05 23:53 UTC
Labels: bad, common, difficult, risky
