### ISSUE TITLE
"Bad state: No element" with trailing comma

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dart_style#523] opened 2016-08-24 17:37 UTC
I added a comma to line 22 of this file:
https://github.com/flutter/flutter/blob/6e9bbca401ad76bba4b5647ea313e74a43259bb3/packages/flutter/lib/src/widgets/animated_size.dart
...and got the following when running the formatter with `dartfmt -l 120 -w *.dart`:
```
Hit a bug in the formatter when formatting animated_size.dart.
Please report at: github.com/dart-lang/dart_style/issues
Bad state: No element
#0      List.last (dart:core-patch/growable_array.dart:218)
#1      SourceVisitor.visitParameterMetadata (package:dart_style/src/source_visitor.dart:1693)
#2      SourceVisitor.visitFieldFormalParameter (package:dart_style/src/source_visitor.dart:839)
#3      FieldFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:4420)
#4      SourceVisitor.visit (package:dart_style/src/source_visitor.dart:1669)
#5      SourceVisitor.visitDefaultFormalParameter (package:dart_style/src/source_visitor.dart:690)
#6      DefaultFormalParameterImpl.accept (package:analyzer/src/dart/ast/ast.dart:3390)
#7      SourceVisitor.visit (package:dart_style/src/source_visitor.dart:1669)
#8      SourceVisitor._visitTrailingCommaParameterList (package:dart_style/src/source_visitor.dart:2065)
#9      SourceVisitor.visitFormalParameterList (package:dart_style/src/source_visitor.dart:886)
#10     FormalParameterListImpl.accept (package:analyzer/src/dart/ast/ast.dart:4725)
#11     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:1669)
#12     SourceVisitor._visitBody (package:dart_style/src/source_visitor.dart:1865)
#13     SourceVisitor.visitConstructorDeclaration (package:dart_style/src/source_visitor.dart:612)
#14     ConstructorDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:2892)
#15     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:1669)
#16     SourceVisitor.visitClassDeclaration (package:dart_style/src/source_visitor.dart:438)
#17     ClassDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:1847)
#18     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:1669)
#19     SourceVisitor.visitCompilationUnit (package:dart_style/src/source_visitor.dart:523)
#20     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2439)
#21     SourceVisitor.visit (package:dart_style/src/source_visitor.dart:1669)
#22     SourceVisitor.run (package:dart_style/src/source_visitor.dart:100)
#23     DartFormatter.formatSource (package:dart_style/src/dart_formatter.dart:130)
#24     processFile (package:dart_style/src/io.dart:75)
#25     formatPaths (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/third_party/pkg_tested/dart_style/bin/format.dart:222)
#26     main (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/third_party/pkg_tested/dart_style/bin/format.dart:152)
#27     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#28     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by munificent** [comment] 2016-08-24 19:04
Duplicate of #520.

**Closed by munificent** 2016-08-24 19:04 UTC
