### ISSUE TITLE
Indentation of 6, should be 4

### ISSUE THREAD

**Issue by zoechi** [dart-lang/dart_style#693] opened 2018-06-06 09:47 UTC
```
class _ChoseVideoWidgetState extends State<ChoseVideoWidget> {
  @override
  Widget build(BuildContext context) => new PopupMenuButton<ImageSource>(
        onSelected: widget.onSelected,
        itemBuilder: (context) => <PopupMenuEntry<ImageSource>>[
              const PopupMenuItem<ImageSource>(
                value: ImageSource.camera,
                child: const Text('Take and add a new photo'),
              ),
            ],
      );
}
```

`onSelected: ...` and `const PopupMenuItem<...`

or was this an intentional change I didn't notice?

https://github.com/dart-lang/dart_style/wiki/Formatting-Rules#indent-continued-lines-with-at-least-four-spaces
does that mean 6 is OK as well? Seems weird to me.

**Comment by munificent** [comment] 2018-06-06 19:22
Ugh, this is yet another weird interaction of the trailing comma style with the other style. The whole body of the method is +4 because of the split after `=>`. Note that the closing `);` is exactly +4. Then the body of the argument list is +2 because of the trailing comma at the end of the `itemBuilder` argument.

So it's working as intended, though it looks kind of funny. If it were me, I would use brace bodies instead of `=>` for the method and function expression.

**Closed by munificent** 2018-06-06 19:22 UTC
Labels: trailing-commas
