### ISSUE TITLE
[0.2.1] Possible problem with formatting single invocation

### ISSUE THREAD

**Issue by scheglov** [dart-lang/dart_style#476] opened 2015-12-08 21:00 UTC
This code:
```
class Foo {
  bar() {
    entry1.setValue(
        ANALYSIS_OPTIONS_ERRORS, <AnalysisError>[error1, error2], []);
  }
}
```

is reformatted to this:
```
class Foo {
  bar() {
    entry1
        .setValue(ANALYSIS_OPTIONS_ERRORS, <AnalysisError>[error1, error2], []);
  }
}
```

I understand that it is good if there is a chain of invocations.
But for a single invocation it seems not quite beneficial.

**Comment by munificent** [comment] 2016-01-13 19:12
Yeah, that doesn't look ideal. I'll see if I can tweak it, but it might be hard given how tied up this is in other kinds of code where these rules produce good results.

**Comment by munificent** [comment] 2016-07-27 23:50
I poked around a bit, but I wasn't able to come up with anything useful. I think the problem is this code is structurally identical to code like:

```dart
class Foo {
  bar() {
    things
        .expand((thing) => thing.isSomething ? [thing, addedStuff, also] : []);
  }
}
```

Here, I think splitting before `.expand()` is the right call because the argument is more conceptually attached to `expand()` than `expand` is conceptually attached to `things`.

On the other hand, the `setValue()` example looks wrong because that methods feels like it is pretty tightly tied to `entry1`. But that's a semantic distinction that, of course, the formatter can't make.

I think in aggregate that the choice to keep parameters with their method probably looks better more often than not, so I'm going to close this out. Sorry.

**Closed by munificent** 2016-07-27 23:50 UTC
Labels: as designed, common, difficult, meh, risky
