### ISSUE TITLE
Warn if dartfmt wasn't able to fully follow the style guide

### ISSUE THREAD

**Issue by lrhn** [dart-lang/dart_style#667] opened 2018-02-05 14:20 UTC
The code:
```dart
if (start == null || start == null || start >= this.length) start = this.length - 1;
```
(which was apparently slightly too long, and also stupid, so good catch) was reformatted to
```
if (start == null || start == null || start >= this.length)
    start = this.length - 1;
```
which is a multi-line if without braces. That's replacing one wrongness with another, without giving any warning.

Would it make sense to at least print a warning in this case?

**Comment by munificent** [comment] 2018-02-09 23:35
Yeah, I think it should notify the user in some way if it fails to produce output that fully satisfies its goals. A similar case is when you have a string literal that doesn't fit in the line length.

**Comment by srawlins** [comment] 2018-11-13 21:30
Duplicate of #564 ?

**Comment by munificent** [comment] 2018-11-14 00:56
Oops, yes!

**Closed by munificent** 2018-11-14 00:56 UTC
Labels: enhancement
