### ISSUE TITLE
Exception on read-only files.

### ISSUE THREAD

**Issue by nellyv** [dart-lang/dart_style#495] opened 2016-02-17 13:14 UTC
A .dart file in our repository is read-only (it is created by a generator and there is no good reason to manually change it). When I run the command to format the other dart files in the repository I get an exception, due to lack of permissions.

You could maybe give a warning, instead (or even nothing) in such cases.

The stack trace:
```
Hit a bug in the formatter when formatting myPath/myFile.dart.
Please report at: github.com/dart-lang/dart_style/issues
FileSystemException: Cannot open file, path = 'myPath/myFile.dart' (OS Error: Permission denied, errno = 13)
#0      _File.throwIfError (dart:io/file_impl.dart:562)
#1      _File.openSync (dart:io/file_impl.dart:413)
#2      _File.writeAsBytesSync (dart:io/file_impl.dart:531)
#3      _File.writeAsStringSync (dart:io/file_impl.dart:555)
#4      _OverwriteReporter.afterFile (package:dart_style/src/formatter_options.dart:119)
#5      processFile (package:dart_style/src/io.dart:77)
#6      formatPaths (file:///mnt/data/b/build/slave/dart-sdk-linux-dev/build/sdk/third_party/pkg_tested/dart_style/bin/format.dart:222)
#7      main (file:///mnt/data/b/build/slave/dart-sdk-linux-dev/build/sdk/third_party/pkg_tested/dart_style/bin/format.dart:152)
#8      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#9      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Command "myPath/third_party/dart-sdk/dart-sdk/bin/dartfmt -w myPath/myFile.dart" failed.
```
```
$ ls -l myPath/
-r--r----- 1 nellyv eng 136666 Feb 17 13:56 myFile.dart
```

**Comment by munificent** [comment] 2016-07-20 22:49
Duplicate of #473.

**Closed by munificent** 2016-07-20 22:49 UTC
Labels: bug, duplicate
