### ISSUE TITLE
Support 4 spaces for indentation

### ISSUE THREAD

**Issue by mfearby** [dart-lang/dart_style#1204] opened 2023-04-05 10:35 UTC
I recently tried Flutter and was surprised to find that the formatter is hard coded to 2 spaces and won't allow users to use 4 spaces.

Please allow us to choose 4 spaces as it makes it easier to see the structure of the code (2 spaces isn't enough).

Not sure if this is related but in Visual Studio code, it inserts un-editable comments at the end of some things which I find distracting and makes it even harder to read the code.

**Comment by jakemac53** [comment] 2023-04-05 16:07
Duplicate of https://github.com/dart-lang/dart_style/issues/534

> Not sure if this is related but in Visual Studio code, it inserts un-editable comments at the end of some things which I find distracting and makes it even harder to read the code.

This is a VsCode thing not related to the formatter, if I understand correctly what you are talking about. cc @DanTup could likely help with disabling it.

**Closed by jakemac53** 2023-04-05 16:07 UTC
Labels: as designed

**Comment by DanTup** [comment] 2023-04-05 16:15
> Not sure if this is related but in Visual Studio code, it inserts un-editable comments at the end of some things which I find distracting and makes it even harder to read the code.

These are "closing labels" aimed to help match up closing parens/brackets with where they started. You can disable them with this setting:

<img width="1217" alt="Screenshot 2023-04-05 at 17 15 10" src="https://user-images.githubusercontent.com/1078012/230141491-64735064-32d3-43ae-9e2e-0a96cd2eb27d.png">
