### ISSUE TITLE
Named params in multi-line annotations should use map-like indent

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/dart_style#251] opened 2015-05-11 18:38 UTC
Formatting the following should be a noop:

```dart
@Component(
  selector: "my-button",
  properties: const [
    "foo",
    "bar",
    "baz",
  ]
)
```

But instead you get this:

```dart
@Component(
    selector: "my-button",
    properties: const [
      "foo",
      "bar",
      "baz",
    ]
)
```

**Comment by munificent** [comment] 2015-05-13 17:48
This is working as intended. Named args indent +4. If you don't do that, it interacts in nasty ways with other formatting rules. For example:

```dart
function(argument, argument,
    argument,
  named: argument,
  another: named);
```

Or:

```dart
function(
    inner(argument, argument,
        wrapped),
  named: inner(argument, argument,
        wrapped)); // <-- where does this go?
```

In general, the formatter only uses block-like wrapping (i.e. +2 spaces) when the content has a closing delimiter that goes on its own line: `]` or `}`. With `)`, we don't move it to the next line. It's this:

```dart
function(
  named: argument,
  another: named);
```

Not:

```dart
function(
  named: argument,
  another: named
);
```

That's unlikely to change because it would affect *tons* of code if we started moving the closing `)` to the next line in argument lists.

**Comment by yjbanov** [comment] 2015-05-13 18:03
This feature request is to treat annotations as special. While annotations use constructor-ish syntax, they are semantically "bags of properties" in almost all cases in practice, and therefore I think it is more appropriate to use map-like indent and parenthesis styling. Functions and constructor invocations should continue to follow the existing rules.

Should we move the discussion to misc just to validate these assumptions?

**Comment by munificent** [comment] 2015-05-14 14:14
We can if you want, but I don't see why annotations should get special treatment. Many functions with named parameters are also used in a DSL-like "bag of properties" way. I think the output for your example should be:

```dart
@Component(
    selector: "my-button",
    properties: const [
  "foo",
  "bar",
  "baz",
])
```

**Comment by yjbanov** [comment] 2015-05-15 23:38
I actually haven't seen many function calls with "bag or properties" semantics. Also, _many_ is different from _most_. 1% of function calls is many. My impression though is that _most_ (if not all) annotations with named parameters (that don't fit in 80 characters of course) match the semantics of map.

**Closed** 2015-05-18 16:27 UTC
Labels: as designed
