### ISSUE TITLE
One-argument functions with a very long multi-part string literal argument are formatted poorly

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dart_style#526] opened 2016-08-24 18:13 UTC
This Flutter code:
```dart
      throw new FlutterError(
        'Incorrect GlobalKey usage.\n'
        '$message'
      );
```
...is formatted by dartfmt as the less readable:
```dart
      throw new FlutterError('Incorrect GlobalKey usage.\n'
          '$message');
```

**Comment by munificent** [comment] 2016-08-24 19:06
Duplicate of #133.

**Closed by munificent** 2016-08-24 19:06 UTC
