### ISSUE TITLE
dartfmt --fix misses `const` in annotation.

### ISSUE THREAD

**Issue by har79** [dart-lang/dart_style#744] opened 2018-10-09 17:15 UTC
For example, running `dartfmt --fix` on

```
@Timeout(const Duration(minutes: 15))
import 'package:test/test.dart';
```

has no effect. Expected behaviour is to remove the const in the annotation.

**Comment by munificent** [comment] 2018-10-09 19:58
Dupe of #720 which is already fixed and published (but not yet rolled internally into Google).

**Closed by munificent** 2018-10-09 19:58 UTC
Labels: duplicate
