### ISSUE TITLE
Strange formatting of list literal type 

### ISSUE THREAD

**Issue by rakudrama** [dart-lang/dart_style#543] opened 2016-09-23 17:42 UTC
This weird breaking of the list literal is from pkg/compiler/lib/src/ssa/optimize.dart

```
@@ -1051,7 +1051,8 @@ class SsaInstructionSimplifier extends HBaseVisitor
         HInstruction result = new HInvokeDynamicMethod(
             selector,
             input.instructionType, // receiver mask.
-            <HInstruction>[input, input], // [interceptor, receiver].
+            <
+                HInstruction>[input, input], // [interceptor, receiver].
             toStringType)..sourceInformation = node.sourceInformation;
         return result;
       }
```

**Comment by srawlins** [comment] 2016-10-06 22:24
smaller repro:

```dart
void f() {
  return //comment
   <String>[]..addAll(["Hey"])..addAll(["There"]);
}
```

becomes

```dart
void f() {
  return //comment
      <
          String>[]..addAll(["Hey"])..addAll(["There"]);
}
```

**Comment by bholtz** [comment] 2016-10-11 20:13
I'm wondering about this too. The proper formatting of type parameters is not addressed in the style guide, AFAIK. Not sure if it should be, but it does leave this in an ambiguous place

**Comment by munificent** [comment] 2016-10-11 20:43
> The proper formatting of type parameters is not addressed in the style guide, AFAIK. Not sure if it should be, but it does leave this in an ambiguous place

The style guide is pretty terse on formatting specifically because we have the automated formatter. If we were to specify all of the formatting rules in prose, it would be massive. We could probably just remove all of the human-readable rules and have a guideline that says, "Whatever dartfmt produces is the correct style." :)

In this case, it's just a bug. The line comment before the type argument is putting it into a weird state. It should be fairly straightforward to fix.

**Comment by munificent** [comment] 2017-03-14 23:18
Duplicate of #589.

**Closed by munificent** 2017-03-14 23:18 UTC
Labels: difficult, rare, safe, wrong
