### ISSUE TITLE
Tall Style: Could we auto-fix missing parenthesis/curly braces?

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/dart_style#1553] opened 2024-09-04 13:34 UTC
One of the common pain points with Flutter formatting is to forget a closing `)`/`}`/etc...

Since with Tall Style we're trying to automate stuff out, would it maybe be possible to automatically fix those when a known solution is found?

For example, given:

```dart
Class(() {

);
```

Realistically, the only solution is to add `}` before `);`.

I assume we wouldn't be able to get a 100% fix rate on those issues, but we can probably automatically fix a good amount of them.

**Comment by munificent** [comment] 2024-09-04 22:38
This is a duplicate of #654.

It's definitely not a bad idea.

However, the formatter relies on the analyzer parser to parse code and that parser doesn't have any specified way of doing error recovery. If the formatter starts accepting code with syntax errors, then if the analyzer parser changes the way it does error recovery, the result could be different formatted output.

I think it's important for the analyzer team to be able to freely improve error recovery. But I also think it's important that the formatter's output be reliably stable. So pragmatically, that makes it hard to implement and test this feature. Any tests I would write could end up spontaneously failing if the parser's error recovery is changed.

Now that I think about it, there's a much worse problem. When the parser does error recovery, it may discard pieces of the syntax tree that aren't correct and that it couldn't figure out how to fix up. If the formatter were to then accept that input and format it, the result is that the formatter could delete code. Given that many users have the formatter run on save, the *last* thing you want is a missing semicolon somewhere in the file causing half your unsaved code to get trashed.

Ultimately, I think the formatter isn't the right place for these kinds of fixes. It's better to do them in the IDE where the user can interact with the parser more directly.

**Closed by munificent** 2024-09-04 22:38 UTC
