### ISSUE TITLE
Possible to --fix lints like pascal case for classes?

### ISSUE THREAD

**Issue by lukepighetti** [dart-lang/dart_style#777] opened 2019-03-01 16:11 UTC
Hi there!

Used `--fix` today and it worked quite nicely!

I was wondering if it's possible to handle issues like:

Before
```
class foo {}

main(){
  final Foo = foo();
}
```

After
```
class Foo{}

main(){
  final foo = Foo();
}
```

**Comment by munificent** [comment] 2019-03-01 22:21
No, this is out of scope for dartfmt. The formatter, by design, does not do any static analysis on code beyond simply parsing the syntax. This is important because:

1. It's *much* faster.
2. It lets you run the formatter on individual files without them needing to be part of a larger program, package, etc.
3. It lets you format code that contains type or other compile-time errors. This is important because formatting is often an early step in getting some broken code healthy again.

@danrubel, is this something you'd consider for dartfix?

**Closed by munificent** 2019-03-01 22:21 UTC

**Comment by lukepighetti** [comment] 2019-03-02 00:23
Cool, didn't know about `dartfix` until now. Will wait for Dan to reply. :)

**Comment by danrubel** [comment] 2019-03-05 13:10
Good thought. I opened an [issue](https://github.com/dart-lang/sdk/issues/36111), but not sure when I'll have a chance to implement it.
