### ISSUE TITLE
Keep collapsed blocks

### ISSUE THREAD

**Issue by dovahkiin98** [dart-lang/dart_style#878] opened 2019-12-05 14:49 UTC
When I format the code, everything that is collapsed just expands again. Which isn't convenient when trying to focus on one block of  code, and you just wanna format that block without having to search that block again, since expanding everything will scroll the editor.

**Comment by srawlins** [comment] 2019-12-05 15:35
Please give an example of code that you try to format, and your expected result, and the actual result.

**Comment by natebosch** [comment] 2019-12-05 19:35
Duplicate of https://github.com/dart-lang/dart_style/issues/876

Code folding in your IDE isn't something that can be controlled by `dartfmt`. Please follow up with the issue tracker for the Dart plugin on whichever IDE you are using. See the linked issue for issue tracker links for intellij and VS code.

**Closed by natebosch** 2019-12-05 19:35 UTC
