### ISSUE TITLE
Crash due to `no-break space` character

### ISSUE THREAD

**Issue by mannprerak2** [dart-lang/dart_style#933] opened 2020-06-26 20:04 UTC
This took a while to track down, but i narrowed it down to this line in a 20,000 line file.
The dartfmt raised the following error.
```
Hit a bug in the formatter when formatting generated_bindings.dart.
The formatter produced unexpected output. Input was:
/// * * *  

Which formatted to:
/// * * *

Please report at github.com/dart-lang/dart_style/issues.
```
The last character of input is actually this unicode character

  | Unicode character | Oct | Dec | Hex
-- | -- | -- | -- | --
\x{A0} | no-break space | 0240 | 160 | 0xA0

**Comment by munificent** [comment] 2020-06-29 17:27
Looks like a duplicate of #901.

**Closed by munificent** 2020-06-29 17:27 UTC
