### ISSUE TITLE
Trailing comma changes format of named constructor arguments

### ISSUE THREAD

**Issue by stevemessick** [dart-lang/dart_style#551] opened 2016-11-03 20:28 UTC
Here's the output from dartfmt for identical constructor calls, modulo trailing comma. I expected both to have 2-space indentation. Not sure where the closing paren should go, but I think the first looks better.
```dart
main() {
  new Foo(
    bar: "1111111111111111111111111111111111111111111111111111111111111",
    baz: "2222222222222222222222222222222222222222222222222222222222222",
  );
  new Foo(
      bar: "1111111111111111111111111111111111111111111111111111111111111",
      baz: "2222222222222222222222222222222222222222222222222222222222222");
}

class Foo {
  Foo({bar: "", baz: ""}) {}
}
```
@alexander-doroshko came up with this example. We're trying to update the IntelliJ formatter (which is not dartfmt) to better suit the needs of Flutter. We could use some guidance even if a patch was delayed.

Also see https://youtrack.jetbrains.com/issue/WEB-23958

**Comment by munificent** [comment] 2016-11-03 21:42
This is working as intended. If you use a trailing comma, you get list-like formatting—two spaces of indentation, each element on its own line, and the closing delimited on its own line.

Yes, it's inconsistent with how code without the trailing comma is formatted. It means you have to remember to either use or do not use trailing commas consistently if you want consistently formatted code.

**Closed by munificent** 2016-11-03 21:42 UTC

**Comment by stevemessick** [comment] 2016-11-03 22:13
Hmm, ok. I'll just leave this here for reference:
https://en.wikipedia.org/wiki/Principle_of_least_astonishment

**Comment by munificent** [comment] 2016-11-03 23:28
Trailing commas in argument lists weren't my idea. Since they were added specifically at the behest of Flutter folks, they are formatted pretty much the way Flutter likes them formatted.

¯\_(ツ)_/¯

**Comment by alexander-doroshko** [comment] 2016-11-04 08:55
@munificent One of the problems it brings is that IDE has no clue where to put the caret when pressing Enter after opening '(' in the arguments list. If user is going to type trailing comma then caret should be 2 spaces shifted, if not - 4 spaces, but IDE does't read user's mind yet..

**Comment by munificent** [comment] 2016-11-04 18:25
Yes, I feel your pain. Note that that problem appears in lots of other places too, though, because the formatter globally optimizes the formatting. Say the user types:

```dart
someFunction(argument &&
```

Then hits enter and types:

```dart
someFunction(argument &&
    argument
```

That gets indented +4. Now they type:

```dart
someFunction(argument &&
    argument ||
```

And hit enter. Then add:

```dart
someFunction(argument &&
        argument ||
    argument);
```

At that point, the previous line should be indented another +4. In general, it's not possible to know the correct indentation for a piece of code given only a prefix of it.

But I agree the trailing comma case is particularly egregious. In practice, most other cases are rare.

**Comment by munificent** [comment] 2016-11-04 18:26
cc @abarth @hixie

**Comment by Hixie** [comment] 2016-11-04 18:43
What I wanted for flutter was the trailing comma behavior everywhere if the expression had a newline in it. The trailing comma thing is a compromise to handle dartfmt's constraints.

**Comment by munificent** [comment] 2016-11-04 21:57
Even if dartfmt formatted exactly how the Flutter folks prefer, my understanding is you'd still want trailing commas. Otherwise, given:

```dart
function(
  argument1,
  argument2,
  argument3
);
```

You still can't move `argument3` up a line without also having to adjust the commas.

**Comment by Hixie** [comment] 2016-11-04 22:03
Sure. Trailing commas as a syntax feature is very valuable. IMHO formatting tools should automatically add them when they do multiline wrapping. The compromise was using them as a flag to change which format style is used.

**Comment by munificent** [comment] 2016-11-04 22:09
Ah, got it. Thanks.
