### ISSUE TITLE
Formatter crashes on syntactically but not semantically valid code

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/dart_style#750] opened 2018-11-08 23:01 UTC
This is invalid Dart, but is parse-able:

```dart
class A {
  B();
}
```

This is also invalid Dart, but crashes the formatter:

```dart
class A {
  const B();
}
```

**Comment by munificent** [comment] 2018-11-09 22:47
Nasty! Looks like we're hitting an edge case where analyzer is willing to parse it without a syntax, but gives the formatter an AST that's not complete.

@bwilkerson, any suggestions on how to handle this?

**Comment by munificent** [comment] 2019-09-24 23:16
Dupe of #810 (which is now fixed).

**Closed by munificent** 2019-09-24 23:16 UTC
Labels: bug, duplicate
