### ISSUE TITLE
Order in named argument lists can impact fmt very negatively

### ISSUE THREAD

**Issue by rkj** [dart-lang/dart_style#458] opened 2015-11-05 17:34 UTC
Here is output I like:
```dart
@Component(selector: 'foo-abc-editor', properties: const ['scheme'])
@View(
    directives: const [MaterialCheckboxComponent, NgFor, NgModel,],
    templateUrl:
        'package:my.long.package.name.that.have.an/foo_abc_editor.html',
    styleUrls: const [
      'package:my.long.package.name.that.have.an/foo_abc_editor.scss.css'
    ])
class FooAbcEditorComponent {}
```
and here is the same file with just templateUrl and styleUrls swapped places, result looks terrible:
```dart
@Component(selector: 'foo-abc-editor', properties: const ['scheme'])
@View(directives: const [
  MaterialCheckboxComponent,
  NgFor,
  NgModel,
], styleUrls: const [
  'package:my.long.package.name.that.have.an/foo_abc_editor.scss.css'
], templateUrl: 'package:my.long.package.name.that.have.an/foo_abc_editor.html')
class FooAbcEditorComponent {}
```

**Comment by munificent** [comment] 2015-11-05 23:50
Duplicate of #421.

**Closed by munificent** 2015-11-05 23:50 UTC
