### ISSUE TITLE
Infinite loop on format

### ISSUE THREAD

**Issue by Grohden** [dart-lang/dart_style#767] opened 2019-01-18 00:27 UTC
Not sure what kind of info i can give, but i'm almost sure this is a formatter problem.

I have a code like this:
```dart
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AppIcon
///      fonts:
///       - asset: fonts/AppIcon.ttf
///
///
///

import 'package:flutter/widgets.dart';

class AppIcons {
  AppIcons._();

  static const _kFontFam = 'AppIcon';

  static const IconData icon = IconData(0xe800, fontFamily: _kFontFam);
}
```
When the formatter is ran it end up duplicating the comment section indefinitely.
Pressing `ctrl+s` (save) on AS just makes the file grow indefinitely, pressing `ctrl+alt+l` (format) duplicates the comment one time.

I think that what causes the problem is the import below the comment, when i move it to the begin of the file everything works fine.

Some info that may help:
Android Studio 3.3
Build #AI-182.5107.16.33.5199772, built on December 25, 2018
JRE: 1.8.0_152-release-1248-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
Dart 2.1.0-dev.9.4
Flutter 1.0.0

**Comment by DanTup** [comment] 2019-01-23 17:30
Does this happen if you run `dartfmt` from the command line? I tested it in VS Code, but couldn't reproduce. I pasted your contents and messed with the formatting a little, then ran format.

Server log showed this:

```text
==> {"id":"134","method":"analysis.updateContent","params":{"files":{"/Users/dantup/Desktop/Dart Sample/bin/format/test.dart":{"content":"///\n/// To use this font, place it in your fonts/ directory and include the\n/// following in your pubspec.yaml\n///\n/// flutter:\n///   fonts:\n///    - family:  AppIcon\n///      fonts:\n///       - asset: fonts/AppIcon.ttf\n///\n///\n///\n\nimport 'package:flutter/widgets.dart';\n\nclass AppIcons {\n  AppIcons._();\n\n  static const _kFontFam = 'AppIcon';\n\n              static const IconData icon =\n\n\n               IconData(0xe800, fontFamily: _kFontFam);\n}\n","type":"add"}}},"clientRequestTime":1548264426939}
<== {"id":"134","result":{}}
==> {"id":"141","method":"edit.format","params":{"file":"/Users/dantup/Desktop/Dart Sample/bin/format/test.dart","lineLength":80,"selectionLength":0,"selectionOffset":0},"clientRequestTime":1548264436512}
<== {"id":"141","result":{"edits":[{"offset":0,"length":449,"replacement":"///\n/// To use this font, place it in your fonts/ directory and include the\n/// following in your pubspec.yaml\n///\n/// flutter:\n///   fonts:\n///    - family:  AppIcon\n///      fonts:\n///       - asset: fonts/AppIcon.ttf\n///\n///\n///\n\nimport 'package:flutter/widgets.dart';\n\nclass AppIcons {\n  AppIcons._();\n\n  static const _kFontFam = 'AppIcon';\n\n  static const IconData icon = IconData(0xe800, fontFamily: _kFontFam);\n}\n"}],"selectionOffset":0,"selectionLength":0}}
==> {"id":"142","method":"analysis.updateContent","params":{"files":{"/Users/dantup/Desktop/Dart Sample/bin/format/test.dart":{"edits":[{"id":"","length":17,"offset":388,"replacement":""},{"id":"","length":12,"offset":348,"replacement":""}],"type":"change"}}},"clientRequestTime":1548264436519}
<== {"id":"142","result":{}}
```

**Comment by munificent** [comment] 2019-01-23 20:38
I can't reproduce this running dartfmt from the command line. (I would be pretty surprised if I could because this code looks pretty typical and a bug this severe likely would have shown up by now.)

Could this be caused by some other tool or plug-in in your editor? Maybe something trying to auto-organize imports (which dartfmt doesn't do)?

**Comment by Grohden** [comment] 2019-01-23 22:59
@DanTup @munificent 
Ok, the `dartfmt` from the command line works - i thought that the `dartfmt` organized the imports...

Anyway, this is a Android Studio problem, when the "Organize imports on save" option is checked the problem happens
![image](https://user-images.githubusercontent.com/7496871/51642713-4dd30d80-1f51-11e9-8cb1-ca1f7bb06fbc.png)

**Comment by munificent** [comment] 2019-01-24 06:19
OK, closing the issue here since it isn't in dartfmt. I'm not sure where you'd go to file the Android Studio issue, sorry.

**Closed by munificent** 2019-01-24 06:19 UTC
Labels: bug, needs info

**Comment by DanTup** [comment] 2019-01-24 08:21
I can repro duplication of comments when running `Organize Imports` in VS Code so I've opened an analyzer bug here:

https://github.com/dart-lang/sdk/issues/35744

However I also think there may be a bug in the AS/IntelliJ plugin if it's resulting in an infinite loop, so I've also opened an issue there:

https://github.com/flutter/flutter-intellij/issues/3117

**Comment by Grohden** [comment] 2019-01-24 11:06
@munificent thx for the help

@DanTup thx for opening those issues, i will watch them and i see if i can help
