### ISSUE TITLE
Default line length 80 is not enough for wrapped widgets,a .editorconfig like file is necessary

### ISSUE THREAD

**Issue by hugetiny** [dart-lang/dart_style#1172] opened 2023-02-10 12:05 UTC
dart format does not  contain a .editorconfig file.
So codes become hard to read when wrapped widgets grows.
at least 200 or more is good choice for default line length.

**Comment by munificent** [comment] 2023-02-16 01:39
Merging this issue as a duplicate of #918.

**Closed by munificent** 2023-02-16 01:39 UTC
