### ISSUE TITLE
Formatter failure with annotated for-loop variable

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/dart_style#640] opened 2017-06-28 04:50 UTC
```
Hit a bug in the formatter when formatting /usr/local/google/home/paulberry/dart-test/sdk/pkg/front_end/testcases/inference/downwards_inference_annotations_for_loop_variable.dart.
The formatter produced unexpected output. Input was:
// Copyright (c) 2017, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/*@testedFeatures=inference*/
library test;

class Foo {
  const Foo(List<String> l);
}

void test() {
  for (@Foo(/*@typeArgs=String*/ const []) int i = 0; i /*@target=num::<*/< 1; i++) {}
  for (@Foo(/*@typeArgs=String*/ const []) int i in /*@typeArgs=int*/[0]) {}
}

main() {}

Which formatted to:
// Copyright (c) 2017, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.

/*@testedFeatures=inference*/
library test;

class Foo {
  const Foo(List<String> l);
}

void test() {
  for (@Foo(/*@typeArgs=String*/ const [])
  int i = 0;
      i /*@target=num::<*/ < 1;
      i++) {}
  for (int i in /*@typeArgs=int*/ [0]) {}
}

main() {}

Please report at github.com/dart-lang/dart_style/issues.
```

**Comment by munificent** [comment] 2018-02-21 00:28
Duplicate of #648.

**Closed by munificent** 2018-02-21 00:28 UTC
Labels: bad, easy, rare, safe
