### ISSUE TITLE
support formatting of code segments

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/dart_style#710] opened 2018-07-12 16:44 UTC
Formatting tools work the best when there are no changes to the style format and when every single change to a file is formatted. In this "perfect" world, you have the nice effect that the only format changes you see on a change are related to the actual changes the developer made.

When the formatting tool changes, which invariably has to, there are two options: format the file as you modify it or land a formatting change on its own before continuing development. The former has the disadvantage that code-reviews get noisy with unrelated formatting changes, and both have the disadvantage that the blame history gets noisy too, making it harder to find where certain semantic changes were made.

To compensate for that, some code management repos have support for invoking formatting tools with only the sections of the file that were modified. This makes formatting more incremental, but eliminates the noise as only lines that were already modified by the user end up being formatted.

I'm not familiar at all with the implementation, but I recall long ago @munificent had mentioned that it was hard to only do formatting in the middle because of the additional context that comes from preceding statements and scopes. If it can't be done only on modified lines, maybe it is possible to pick a minimal subtree that can be formatted independently of the rest of the file? For example, maybe only format the enclosing block, loop, or method where a statement was modified?

**Comment by munificent** [comment] 2018-07-12 17:57
Duplicate of #92.

**Closed by munificent** 2018-07-12 17:57 UTC
Labels: enhancement
